### ISSUE TITLE
Upgrade to support puppeteer 1.0.0 

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#10]
same as https://github.com/peterbe/minimalcss/issues/33

**Comment by jonathaningram** [comment]
@stereobooster do you know if this is this a big change for react-snap? Looking at the release notes (https://github.com/GoogleChrome/puppeteer/releases/tag/v1.0.0) it doesn't look like too many actual API changes.

**Comment by stereobooster** [comment]
I suppose not, but we also need to upgrade minimalcss

**Comment by stereobooster** [comment]
Created this PR https://github.com/stereobooster/react-snap/pull/123

**Comment by stereobooster** [comment]
fixed in 1.11.0
