### ISSUE TITLE
Is Node 8 required?

### ISSUE THREAD

**Issue by bkrall** [stereobooster/react-snap#100]
### If you are reporting a bug

When I try installing `react-snap` I'm getting this message, but don't see Node 8 as a prereq for installing.  Do I need to upgrade from node v7 to use this? 

> [2/4] 🚚  Fetching packages...
error sourcemapped-stacktrace-node@2.1.6: The engine "node" is incompatible with this module. Expected version ">= 8.6.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by stereobooster** [comment]
I tested it only against node 8, this is why package specifies node version. If you want to test with node 7 you can fork repo, change what you need and install your work with github url

**Comment by bkrall** [comment]
Got it, thanks!
