### ISSUE TITLE
Open-source frustration: maintainer vs user

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#103]
There are [a lot of prerenderers out there](https://github.com/stereobooster/react-snap/blob/master/doc/alternatives.md). Most of them are not supported - tickets are open without response for months. A lot of frustrated users who open tickets or PRs and have no response.

👿 On one side I feel sad about all that frustration people get. I always tempted to jump into the tickets and say: "Hey, this problem is solved in my project, use it".

😇 On the other side, it feels wrong to promote my project on the other projects issue tracker.

I'm not saying I'm an ideal open source maintainer. Instead, I vastly simplified my project, choose convention over configuration which allows me spent less time supporting code. I use strict rules about issue reports - a reproducible demo is required.

I'm not saying my project is ideal. It misses detailed documentation about options (but also it promotes to use as less as possible options ). It misses tests.

I believe my project has some parts right: 
- convention over configuration
- proper abstractions which allow to not dependent on frontend frameworks
- handles different edge cases and has documentation for caveats
- doesn't depend on webpack
- load performance optimisation out of the box

I do understand project authors, who have their personal life and don't have to spend their time to work for free or response to tickets. I grateful for them that they shared their work with the community. I'm open source maintainer myself, I do not get paid for my open source work.

I do understand frustrated users, who try to use project and it fails. 

<details>
<summary>backstory of react-snap (click to open)</summary>

I'm myself tried to use `react-snapshot`. I get into the bug, I reported it, I tried to fix it, realized that fix will not help because I need a full-featured browser. I implemented small script (100 lines of code) just as an experiment.  `react-snap` never meant to be a project until @badsyntax convinced me to create a package. (That is why name choice is so poor.)

Later I added some load performance optimisations. Special thanks to @peterbe for `minimalcss`, which has way fewer stars than it deserves. Thanks to "optimisation" bit my project got into [React Status](https://react.statuscode.com/issues/60), that is when it is started for real. The project got about 500 stars in a week.

I'm as an open-source maintainer know that it is not easy to let go your project. I have [some dead projects](https://github.com/stereobooster/jekyll-press/issues/35) myself. I thought about transfer project ownership (of those dead projects), but this is hard. How do you choose next maintainer? Also, it is hard to maintain project if you are not using it anymore.
</details>

I will try to contact the biggest alternative projects and ask them to step down in favor of `react-snap` because I feel pity for all those frustrated users.

**Comment by stereobooster** [comment]
Well I tried. I have no response. It can happen people are busy with their own life which is perfectly fine.

**Comment by badsyntax** [comment]
Who did you reach out to?

**Comment by badsyntax** [comment]
FYI I found react-snapshot as it was mentioned in the create-react-app docs. You can try get that updated to point to react-snap instead.

**Comment by stereobooster** [comment]
create-react-app contains both links to `react-snapshot` and `react-snap`. Somebody added it. 

> Who did you reach out to

Some authors. It can happen that they even didn't get my message, I believe they have pretty big amount of income messages and it is easy to lost message from some random person on the internet. I even not sure if I chose proper channel for communication or that I was able to express my intentions.

**Comment by osdiab** [comment]
Not to be a downer but given this post @stereobooster I was wondering how I should feel about the large number of issues on this project that have been left open for months without response. I'm currently looking into how I should be doing prerendering, but like you said, there are a lot of choices and it's not straightforward to know which to go with.

**Comment by stereobooster** [comment]
> Not to be a downer 

@osdiab fair point)) You never know when life comes for you.

I'm not doing pre-rendering at the moment so have no idea.
