### ISSUE TITLE
Chrome error when attempting to run react-snap in alpine docker container

### ISSUE THREAD

**Issue by wallslide** [stereobooster/react-snap#109]
I have the following in my `package.json` file:
```
"reactSnap": {
    "puppeteerExecutablePath": "/usr/bin/chromium-browser",
    "puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox", "--disable-gpu"]
  }
```
I am trying to run react-snap in a docker container based on the `alpine-9` image. I have made sure that chrome headless is installed, and can run it from the command line. Issuing `which chromium-browser` returns `/usr/bin/chromium-browser`. I am using `react-snap@1.8.0`

When I try to run react-snap, I get the following error:
```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn /webapp/node_modules/puppeteer/.local-chromium/linux-499413/chrome-linux/chrome ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
error Command failed with exit code 1.
```
It looks like the `puppeteerExecutablePath` command isn't actually working, and puppeteer is trying to run chrome with its local version.  Any ideas? Thanks.

**Comment by stereobooster** [comment]
> It looks like the `puppeteerExecutablePath` command isn't actually working

Yes. It was merged but not published to the npm. Try `1.9.0`

**Comment by wallslide** [comment]
I've updated to `1.9.0` and it seems to be working now, thanks!

**Comment by stereobooster** [comment]
@linonetwo your code is helping people ;)

**Comment by linonetwo** [comment]
Oh, that's cool! Hahaha
