### ISSUE TITLE
Use npm package for loadCss instead of vendoring it

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#11]
Use [npm package for loadCss](https://www.npmjs.com/package/fg-loadcss) instead of vendoring it (see vendor folder).

**Comment by suvratjain1995** [comment]
@stereobooster  Hey I would like to work on this issue. Could you be more descriptive about the changes that should be made.

**Comment by suvratjain1995** [comment]
@stereobooster  I would like to work on this issue.
