### ISSUE TITLE
I just wanted to say thank you

### ISSUE THREAD

**Issue by loganpowell** [stereobooster/react-snap#110]
This is the third static-site solution for React I've tried in a week (after Gatsby and React Static)...

I hoped you had a twitter account so I could thank you publicly, but nothing in your github profile. 
I'd just like to say thank you for making doing this so nice and easy! Please let me know if you'd like to share your twitter handle for a public shoutout. It would be the least I could do.

At any rate, have a wonderful day, sir.

**Comment by stereobooster** [comment]
> This is the third static-site solution for React I've tried in a week (after Gatsby and React Static)

I do not consider this tool to be in the same niche as Gatsby. Gatsby is great. You need to follow Gatsby structure and you get great benefits. I separate 3 approaches: prerendering (I saw it's called lazymorphic), static-site generators, server side rendering (also called isomorphic). See full list [here](https://github.com/stereobooster/react-snap/blob/master/doc/alternatives.md).

My twitter account is the same as github. Thank you for warm words.

**Comment by loganpowell** [comment]
Agreed. It's much easier to get what I needed and still use familiar (and well documented) tools (e.g., CRA)! Twitter love engaged!
