### ISSUE TITLE
Crawling stops after "/ log: Content is cached for offline use."

### ISSUE THREAD

**Issue by linonetwo** [stereobooster/react-snap#111]
Crawling stops here:

<img width="397" alt="wx20180109-100221 2x" src="https://user-images.githubusercontent.com/3746270/34701621-46fbf2a4-f524-11e7-8151-0220622f8acf.png">

Normally, it should be like this:

<img width="429" alt="wx20180109-100328 2x" src="https://user-images.githubusercontent.com/3746270/34701645-6018f296-f524-11e7-8e1a-6ae146a84013.png">

What could cause it to stop here?

**Comment by linonetwo** [comment]
Reproducible Dockerfile is 

```dockerfile
# Dockerfile.alpine
FROM mhart/alpine-node:9
RUN apk update && \
    apk upgrade && \
    apk add --update ca-certificates && \
    apk add bash git openssh chromium --update-cache --repository http://nl.alpinelinux.org/alpine/edge/community \
    rm -rf /var/cache/apk/*

# If you have native dependencies, you'll need extra tools
# RUN apk add --no-cache make gcc g++ python

# Setup yarn
RUN yarn config set registry https://registry.npm.taobao.org

# Create app directory and bundle app source
RUN mkdir -p /usr/src/app

# use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
COPY package.json /tmp/package.json
COPY yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app/

# simple http server
RUN yarn global add serve

# From here we load our application's code in, therefore the previous docker
# "layer" thats been cached will be used if possible
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN yarn build
# Expose port
EXPOSE 5000

CMD [ "serve", "-s", "./build" ]
```

**Comment by linonetwo** [comment]
I wonder whether it is related to https://github.com/stereobooster/react-snap/issues/10 , since I'm using latest chromium here.

**Comment by stereobooster** [comment]
Try to limit number of simultaneously open tabs

```
concurrency: 1,
```

Maybe disable `inlineCss`. 

Can be connected to https://github.com/stereobooster/react-snap/pull/108

**Comment by linonetwo** [comment]
It's inlineCss .

I wonder why. Maybe I should look at the implementation.

**Comment by stereobooster** [comment]
> It's inlineCss .

I saw same problem with Heroku. I suppose it is good idea to add it to troubleshooting section

**Comment by linonetwo** [comment]
I think the cause is https://github.com/peterbe/minimalcss/blob/master/src/run.js#L77 . It uses the wrong puppeteerExecutablePath. 

Maybe we should pass puppeteerExecutablePath all the way to minimalcss, so it will work in docker too.

**Comment by stereobooster** [comment]
It should not, because `react-snap` passes instance of browser in it

```js
  const minimalcssResult = await minimalcss.minimize({
    urls: [pageUrl],
    skippable: request =>
      options.skipThirdPartyRequests && !request.url.startsWith(basePath),
    browser: browser,
    userAgent: options.userAgent
  });
```
