### ISSUE TITLE
Using this with S3?

### ISSUE THREAD

**Issue by bkrall** [stereobooster/react-snap#113]
I did a pretty deep dive on this and have to say, kudos to @stereobooster on this repo and your responsiveness to issues. 

I was able to get this working on my project.  When I run `react-snap`, it's pre-rending the pages I want and I'm pretty happy.  I have a client-side React app hosted on S3 through Cloudfront that I'd like to be able to customize SEO/meta tags on. 

Once I generated the pages I would like to prerender, I'm a bit confused on next steps.  I could upload the files to S3, but since the route is the same as the one specified on `react-router`, instead it uses that page.

For ex., I have a route in `react-router` named /faq 

And `react-snap` created an FAQ directory with an index.html file in it.  I'd love for Facebook's Sharing Debugger to render the meta tags from the FAQ directory, rather than the SPA content that's being served up currently.  Any chance you can point me in the right direction to make that happen?

**Comment by stereobooster** [comment]
bucket -> properties -> Static website hosting
<img width="522" alt="screen shot 2018-01-11 at 22 26 30" src="https://user-images.githubusercontent.com/179534/34848309-960c34c0-f71e-11e7-8ed4-7df2a7cd6d90.png">

bucket -> permissions-> bucket policy
```
{
    "Version": "2012-10-17",
    "Id": "Policy1505500058737",
    "Statement": [
        {
            "Sid": "Stmt1505499902974",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3::..."
        }
    ]
}
```

Configure CloudFront to respect existing headers. Set expiration header for serviceWorker.js (if use one) to `max-age=0`. See this script: https://github.com/stereobooster/an-almost-static-stack/blob/react-snap/scripts/aws-deploy.js

**Comment by bkrall** [comment]
@stereobooster thanks for the bucket policy example.

I tried this on a test environment and found when I did a new deployment and ran Cloudfront invalidations, I would get an `AccessDenied` message when I visited the site. If I manually changed the root index.html file to "Make public", it becomes accessible.

Here's what I was using before for reference...

{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::*",
                "arn:aws:s3:::"
            ]
        }
    ]
}`
`
thanks again for your help.

**Comment by stereobooster** [comment]
By `"Resource": "arn:aws:s3::..."` I meant `"Resource": "arn:aws:s3::name_of_the_bucket"`. This policy required for 404 page to work, otherwise you will get 403 error. I also set allow list from all clients (in ACL list), but I suppose you can limit to cloudfront IPs only

**Comment by stereobooster** [comment]
I suppose question is resolved one way or another. Feel free to reopen
