### ISSUE TITLE
Dumb question: Can I get route animations using Snap?

### ISSUE THREAD

**Issue by loganpowell** [stereobooster/react-snap#116]
I'm following along with [a tutorial](https://hackernoon.com/animated-page-transitions-with-react-router-4-reacttransitiongroup-and-animated-1ca17bd97a1a) and I just figured I'd ask (I get the feeling the answer is going to be no), but would route animations work in Snap?

**Comment by stereobooster** [comment]
I can't see why not. After react application being rehydrated it works like any other react application. But haven't tried myself

**Comment by loganpowell** [comment]
I've tried it and I can't get it to work with the setup as covered in the tut (with some modifications to make it work with the latest version of React Transition Group (which I've got working). When I add React Snap, the animations are gone.

I'm digging and found this:

https://github.com/zeit/next.js/issues/88#issuecomment-284693637

It seems like a common symptom.

**Comment by stereobooster** [comment]
I will try this example tomorrow https://github.com/maisano/react-router-transition. Or you can suggest yours

**Comment by loganpowell** [comment]
Here's the example I'm working with:

https://github.com/loganpowell/router-transition-animation

**Comment by stereobooster** [comment]
https://github.com/maisano/react-router-transition doesn't work out of the box it needs more time to be configured

**Comment by stereobooster** [comment]
As of your example, you are using React 15, but `hydrate` is the feature of React 16.

This code works:
```js
import React from 'react';
import { render } from 'react-dom';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './index.css';

const rootElement = document.getElementById('root');
render(<App />, rootElement);

registerServiceWorker();
```

**Comment by stereobooster** [comment]
The strange part is why create-react-app does not report an issue when code imports nonexistent symbol e.g. `hydrate`. Need to open issue in create-react-app tracker

**Comment by loganpowell** [comment]
just upgraded with `yarn upgrade react@next react-dom@next` and now I have another issue:

https://github.com/animatedjs/animated/issues/86

I will go back to 15 and use your fix for now :)

Thank you @stereobooster

**Comment by loganpowell** [comment]
Closing this as your fix worked!
