### ISSUE TITLE
TLS issues with self-signed certificates

### ISSUE THREAD

**Issue by MaxMilton** [stereobooster/react-snap#120]
When making requests with an invalid TLS certificate, e.g. self-signed, puppeteer will throw an error: `Error: SSL Certificate error: ERR_CERT_AUTHORITY_INVALID`.

There's a `puppeteer.launch()` option to ignore these types of errors, `ignoreHTTPSErrors:true` as specified [in the docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions).

There should be a react-snap option to enable this as necessary.

-----

P.s. I totally love the project! I've used a bunch of other solutions in the past but they either didn't work or were so cumbersome and error prone they weren't worth using. Used react-snap for the first time recently and it totally blew my mind! No need to list routes to crawl and the default config is 100/100. Thanks for the hard work!

**Comment by stereobooster** [comment]
Hey. This is not hard to do. Number of puppeteer options increases probably need to create separate section for it in config, like

```json
"puppeteer": {
  "args": ["--no-sandbox", "--disable-setuid-sandbox"],
  "executablePath": "/usr/bin/chromium-browser",
  "ignoreHTTPSErrors": true
}
```

**Comment by MaxMilton** [comment]
I like the idea of a "puppeteer": {} section in the options. In that case it's probably worth passing this whole object to puppeteer. Perhaps something simple like:

```javascript
  const browser = await puppeteer.launch(Object.assign({
    handleSIGINT: false
  }, options.puppeteer);
```

**Comment by stereobooster** [comment]
v1.10.0 - `puppeteerIgnoreHTTPSErrors: false`. I will do breaking changes in v2

**Comment by alan345** [comment]
In which file should I add this code? `package.json`?

```
"puppeteer": {
  "args": ["--no-sandbox", "--disable-setuid-sandbox"],
  "executablePath": "/usr/bin/chromium-browser",
  "ignoreHTTPSErrors": true
}
```
