### ISSUE TITLE
puppeteer not getting args in ubuntu

### ISSUE THREAD

**Issue by cjimmy** [stereobooster/react-snap#122]
I'm trying to get react-snap to run on a Ubuntu 14.04.5 LTS image on AWS CodeBuild. My issue seems to be related to issue [#290](https://github.com/GoogleChrome/puppeteer/issues/290) for puppeteer.

I've added `"puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"]` to `package.json` in `node_modules/react-snap`
so that this is the config:
```
  "reactSnap": {
    "destination": "tmp",
    "inlineCss": true,
    "cacheAjaxRequests": true,
    "puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"]
  },
```
and print out the contents of `node_modules/react-snap/package.json` to verify that I successfully edited the file.

and I've added all the dependencies noted in #290, but when the script runs react-snap, I end up with this:
```
(node:1840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
[0122/002828.978563:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:1840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm surprised that it doesn't see the `--no-sandbox` arg. Any advice on how to proceed? I'd like to not fork react-snap just to try to launch puppeteer with the same flags.

**Comment by cjimmy** [comment]
That was silly. I was putting `"puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"]` in the wrong place. I should've just read through the code in the first place. It should go under `defaultOptions` in `index.js`. 🙇

I'll close this now, as a tomb to my stupidity, for any future folks who run into a similar problem.

I might also put in a PR to make it clearer in the docs where to add options.

Thanks for this package. React-snap is saving me a lot of work and time!

**Comment by omgpiu** [comment]
> This helped me on WSL / ubuntu.
> 
> Just to be clear, you can add the args to run instead of defaultOptions:
> 
> ```js
> const { run } = require("react-snap");
> 
> await run({
>     // You would have other args here,
>     puppeteerArgs: ["--no-sandbox", "--disable-setuid-sandbox"]
> })
> ```
> 
> #290 above should refer to [puppeteer/puppeteer#290](https://github.com/puppeteer/puppeteer/issues/290)

Where I should add this code?

**Comment by mribbons** [comment]
Hi @omgpiu,
I don't know if the usage of this project has changed since I used it.

My project has something like 
`"postbuild": "node make-static-pages.js"`

and make-static-pages.js contains the puppeteerArgs.

However the readme for this project looks like this:
```
"scripts": {
  "postbuild": "react-snap"
},
"reactSnap": {
  "source": "dist",
  "minifyHtml": {
    "collapseWhitespace": false,
    "removeComments": false
  }
}
```

So I don't know where the puppeteerArgs can be passed now.

**Comment by omgpiu** [comment]
> Hi @omgpiu, I don't know if the usage of this project has changed since I used it.
> 
> My project has something like `"postbuild": "node make-static-pages.js"`
> 
> and make-static-pages.js contains the puppeteerArgs.
> 
> However the readme for this project looks like this:
> 
> ```
> "scripts": {
>   "postbuild": "react-snap"
> },
> "reactSnap": {
>   "source": "dist",
>   "minifyHtml": {
>     "collapseWhitespace": false,
>     "removeComments": false
>   }
> }
> ```
> 
> So I don't know where the puppeteerArgs can be passed now.

Thanks a lot!
