### ISSUE TITLE
[Question] What to do when new pages are added or existing pages are updated?

### ISSUE THREAD

**Issue by wallslide** [stereobooster/react-snap#126]
So I've built my site, I've run react-snap against it, and I've deployed it. And then a user comes and adds a new Event. Now I have an Event page that hasn't been pre-rendered, and as far as I know, I have to rebuild my site, re-run react-snap, and redeploy it. Is there an easier way? Can I just tell react-snap to crawl a single, specific URL, or a specific set of URLs?

If this functionality doesn't exist, I feel like it could be very useful. Thanks!

**Comment by stereobooster** [comment]
This is interesting idea I thought about something similar, but this is out of project scope (at least for now). 

What you can do right now is use programmatic API:

```js
const { run } = require("react-snap");
run({
  includes: ["/new-page-1", "/new-page-2"]
  crawl: false
});
```

Do not forget the case about deleting, renaming and updating items.

**Comment by stereobooster** [comment]
I suppose question is resolved one way or another. Feel free to reopen

**Comment by eurobob** [comment]
Does this solution still work? When I try this example it only does the root page and not any of the included urls

**Comment by eurobob** [comment]
Ah, the "includes" option needs to be "include".

It's also missing a comma at the end of the line
