### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by baptooo** [stereobooster/react-snap#129]
Hello @stereobooster first I would like to thank you for this package, very nice job :+1:

I wonder if you would add a changelog for releases plz ?
This could help understanding how the library evolves :innocent:

Thank you !

**Comment by baptooo** [comment]
Oups already mentionned here https://github.com/stereobooster/react-snap/issues/90

**Comment by stereobooster** [comment]
I maintain this library alone (also contributing to minimalcss). I have limited time, that is why some good practices have been neglected, like tests, changelog, documentation of all available options. I chose features and documenting caveats over good practices (listed above).

Though I have some excuses:
- changelog - always update to the latest version. I'm trying not to break things. Only breaking change was between 0.x and 1.x.
- documentation for options - you should use as less as possible options. All options required to overcome caveats are documented
