### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#13]
If you use project and especially experimental features, like `inlineCss` or `preloadResources`. Drop by to say how it goes. It would be nice if you show webpagetest.org report before and after.

**Comment by Lemmih** [comment]
I use react-snap for https://github.com/Lemmih/ClozeCards. Don't use `inlineCss` as it triggers some errors and I haven't had the time to investigate.

**Comment by stereobooster** [comment]
Added one myself https://github.com/stereobooster/react-snap/blob/master/doc/an-almost-static-stack-optimization.md
