### ISSUE TITLE
Navigation Timeout Exceeded

### ISSUE THREAD

**Issue by lewisdonovan** [stereobooster/react-snap#131]
I'm getting `Error: Navigation Timeout Exceeded: 30000ms exceeded` when running react-snap locally. It renders all the top-level pages as expected, and then when it hits the first detail-view URL it throws the error.

It wasn't doing this before and I haven't changed any code in the component, although the page itself is new, as new items have been added to the CMS and are now being pulled from the API. I have tried removing the offending item and running build again, but the same error happens when it gets to the first detail-view URL again (even though it's a different item).

Error log pasted below:

```
info it worked if it ends with ok
verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
info using npm@5.6.0
info using node@v8.9.3
verbose run-script [ 'prebuild', 'build', 'postbuild' ]
info lifecycle magician-prod@0.1.0~prebuild: magician-prod@0.1.0
info lifecycle magician-prod@0.1.0~build: magician-prod@0.1.0
verbose lifecycle magician-prod@0.1.0~build: unsafe-perm in lifecycle true
verbose lifecycle magician-prod@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dono023/Desktop/react-projects/magician-prod/node_modules/.bin:/Users/dono023/torch/install/bin:/Applications/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/you/torch/install/bin
verbose lifecycle magician-prod@0.1.0~build: CWD: /Users/dono023/Desktop/react-projects/magician-prod
silly lifecycle magician-prod@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
silly lifecycle magician-prod@0.1.0~build: Returned: code: 0  signal: null
info lifecycle magician-prod@0.1.0~postbuild: magician-prod@0.1.0
verbose lifecycle magician-prod@0.1.0~postbuild: unsafe-perm in lifecycle true
verbose lifecycle magician-prod@0.1.0~postbuild: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dono023/Desktop/react-projects/magician-prod/node_modules/.bin:/Users/dono023/torch/install/bin:/Applications/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/you/torch/install/bin
verbose lifecycle magician-prod@0.1.0~postbuild: CWD: /Users/dono023/Desktop/react-projects/magician-prod
silly lifecycle magician-prod@0.1.0~postbuild: Args: [ '-c', 'react-snap' ]
silly lifecycle magician-prod@0.1.0~postbuild: Returned: code: 1  signal: null
info lifecycle magician-prod@0.1.0~postbuild: Failed to exec postbuild script
verbose stack Error: magician-prod@0.1.0 postbuild: `react-snap`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
verbose stack     at emitTwo (events.js:126:13)
verbose stack     at EventEmitter.emit (events.js:214:7)
verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
verbose stack     at emitTwo (events.js:126:13)
verbose stack     at ChildProcess.emit (events.js:214:7)
verbose stack     at maybeClose (internal/child_process.js:925:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
verbose pkgid magician-prod@0.1.0
verbose cwd /Users/dono023/Desktop/react-projects/magician-prod
verbose Darwin 16.7.0
verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
verbose node v8.9.3
verbose npm  v5.6.0
error code ELIFECYCLE
```

**Comment by stereobooster** [comment]
Can be related https://github.com/GoogleChrome/puppeteer/issues/1908, https://github.com/peterbe/minimalcss/issues/112

**Comment by stereobooster** [comment]
What version of `react-snap` do you use? If it is `1.11` can you try `1.10`?

**Comment by lewisdonovan** [comment]
Rolling back to `1.10.0` seems to be solving this

**Comment by stereobooster** [comment]
In `1.11.0` I update to the latest Puppeteer 1.0. I suspect they broke something

**Comment by gopchi** [comment]
Having the same issue here, but with no effect when rolled back to 1.10.0. Any ideas?

**Comment by stereobooster** [comment]
@gopchi do you have some third-party resources? Can you try to create reproducible example? DId you tried `rm node_modules && yarn install`?

**Comment by gopchi** [comment]
@stereobooster doing what you said worked, but now in the postbuild process there is an error saying Unhandled Promise rejection... for some routes. Despite that it builds the routes and they work.

**Comment by stereobooster** [comment]
@gopchi can you copy/paste error message. It can happen that those notifications are from your application, not from `react-snap`

**Comment by gopchi** [comment]
@stereobooster There it is:

`ERROR: The process with PID 13328 (child process of PID 12024) could not be terminated.
Reason: The operation attempted is not supported.
(node:20400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: taskkill /pid 12024 /T /F`

It happens on different route every time I try to build. Sometimes they are all ok except the last one. Other times 4 of the routes get this error.

**Comment by stereobooster** [comment]
@gopchi this sounds like an issue in puppeteer and not the same as described in this ticket. You can try create reproducible demo and open ticket here or in puppeteer issue tracker. If you open ticket here I will try to investigate and eventually will open ticket in puppeteer issue tracker.

**Comment by gopchi** [comment]
@stereobooster Okay, thanks I will open a new issue on this error.

**Comment by stereobooster** [comment]
Closed in favour of https://github.com/stereobooster/react-snap/issues/240
