### ISSUE TITLE
React Helmet metas not updating in SSR files

### ISSUE THREAD

**Issue by lewisdonovan** [stereobooster/react-snap#134]
When I run `yarn run build` locally, my static HTML files have the correct metas from [react-helmet](https://github.com/nfl/react-helmet), but when I push my project to my Docker container on the server, the static files rendered by the build command don't have any dynamic metas from react-helmet, they all have the same values as the metas on the home page. I'm getting no errors in the logs in my local build or in Docker.

**Comment by stereobooster** [comment]
This is something docker specific. To actually fix this issue I will need reproducible demo, I do not have much experience with Docker though.

**Comment by stereobooster** [comment]
I want be able to fix this without reproducible demo.

**Comment by adamsaparudin** [comment]
Sorry bumping this issue.. I wanted to provide something.

create-react-app version : 3.0.1
react-snap : ^1.23.0
```js
import React from 'react';
import logo from './logo.svg';
import {Helmet} from "react-helmet";
import './App.css';

function App() {
  return (
    <div className="App">
      <Helmet>
        <title>Test</title>
      </Helmet>

      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```
Generated HTML page
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <link rel="manifest" href="/manifest.json" />
    <title>React App</title>
    <link href="/static/css/main.2cce8147.chunk.css" rel="stylesheet" />
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <script>
    /// Long script
    </script>
  </body>
</html>
```

expected build should have
`<title>Test</title>`
instead of
`<title>React App</title>`

**Comment by stereobooster** [comment]
@adamsaparudin You can open new issue and provide reproducible example (as repository, not code snippet in the comment)

**Comment by alexvandervegt** [comment]
I have the same issue, i suspect it has something todo with the page already being saved before the helmet information is updated.

Is there a way to delay the save?

**Comment by adamsaparudin** [comment]
> I have the same issue, i suspect it has something todo with the page already being saved before the helmet information is updated.
> 
> Is there a way to delay the save?

```json
"reactSnap": {
    "publicPath": "/",
    "include": [
      "/"
    ],
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ],
    "puppeteer": {
      "waitUntil": "networkidle0"
    }
  }
```

I use that config, try run using `yarn react-snap`
