### ISSUE TITLE
Multiple "preconnect" link elements with same href, also "preconnect" link to blob

### ISSUE THREAD

**Issue by Amareis** [stereobooster/react-snap#139]
![image](https://user-images.githubusercontent.com/4806617/36016587-8a65be7e-0d95-11e8-8d3b-905209876b1e.png)
I don't know how reproduce it, but i think that's it related with multiple @import in css from external servers.

**Comment by stereobooster** [comment]
I will try to reproduce

**Comment by stereobooster** [comment]
@Amareis I fixed blob issue, but haven't released it yet. As of multiple preconnects, I haven't reproduced it yet

**Comment by stereobooster** [comment]
And fixed second part of the bug. I will try to release this ASAP

**Comment by stereobooster** [comment]
fixed in v1.11.4
