### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#14]

**Comment by badsyntax** [comment]
Idea idea how you want to start testing this? Any testing framework preferred? I could do something similar to [this](https://github.com/geelen/react-snapshot/pull/44) just test page generation using `jest` snapshots. Or are you looking for specific unit tests?

**Comment by stereobooster** [comment]
jest will do

**Comment by stereobooster** [comment]
Adde basic integration tests - https://github.com/stereobooster/react-snap/pull/172. Still need to more unit tests and improve code quality.
