### ISSUE TITLE
Update README about more Vuejs SSR hydration caveats

### ISSUE THREAD

**Issue by MaxMilton** [stereobooster/react-snap#142]
When using `react-snap` with `vue` and `webpack` + `vue-loader` there's an extra client side hydration caveat worth adding to the readme.

When using react-snap with the `minifyHtml.collapseWhitespace = true` option vue client side hydration will fail because, by default, vue-loader includes whitespace when creating its virtual DOM representation. Since the VDOM and the real DOM are different (VDOM has extra whitespace textNodes), hydration fails.

Took me a while to work out what was going on but it turns out there's an easy solution. In the vue-loader configuration just add `preserveWhitespace: false`. In the official templates this is found in the `vue-loader.conf.js` file. [Info in the vue-loader docs](https://github.com/vuejs/vue-loader/blob/master/docs/en/options.md#preservewhitespace).

If that doesn't make sense please let me know and I'll try to explain better or create an example repo.

**Comment by stereobooster** [comment]
> forEach didn't work for some bizarre reason

because

> The `Element.getElementsByTagName()` method returns a live `HTMLCollection`...
> The `HTMLCollection` interface represents a generic collection (array-like object similar to `arguments`)

To use `forEach` you need to convert `HTMLCollection` to array.
 
> remove scripts added to head by webpack; fix async race condition issue

This case should be handled `react-snap`. If it is not the case for you, please open an issue.

Thanks for tips. I'm not an expert in Vue. I want to experiment with it a bit and add notes to Readme

**Comment by MaxMilton** [comment]
Normally when dealing with a NodeList or HTMLCollection I do something like `[...HTMLCollection].foreach(...` but in my experimenting here it didn't work. I've seen some discussion about a babel transpile issue but it was easier to just use a good old loop. Anyway it's beside the point of this issue thread 🙃

I've opened another issue for the webpack bundle issue: https://github.com/stereobooster/react-snap/issues/145

**Comment by MaxMilton** [comment]
Once I have some free time I'll try to put together a PR with the proposed docs updates.

**Comment by stereobooster** [comment]
Fixed in https://github.com/stereobooster/react-snap/pull/172
