### ISSUE TITLE
Option to inject setup/helper JS into render context

### ISSUE THREAD

**Issue by MaxMilton** [stereobooster/react-snap#143]
FYI: Feature request.

## Feature description

Provide a way to run some setup JavaScript just in the prerendering context; which does not appear in the final rendered page.

## Use case

At the moment it's necessary to include react-snap setup code in your main JS bundle, however, since this code is unnecessary at client runtime it shouldn't live in the client JS bundle.

For example in my vue + webpack projects I have:

```javascript
window.snapSaveState = () => {
  // enable client-side hydration once the page has been prerendered
  document.querySelector('#app').setAttribute('data-server-rendered', 'true');

  // remove scripts added to head by webpack; fix async race condition issue
  const scripts = document.head.getElementsByTagName('script');
  for (let i = 0; i < scripts.length; i += 1) {
    const el = scripts[i];

    if (el.async && el.charset === 'utf-8') {
      el.remove();
    }
  }
};
```

Even though it's not much code when considering the final file size, it's still wasted bytes. Having the ability to run setup code will enable more advanced render time configuration too.

## Implementation details

I still haven't played with puppeteer so much yet but [`page.addScriptTag`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageaddscripttagoptions), [`frame.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#frameevaluatepagefunction-args), or [`executionContext.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#executioncontextevaluatepagefunction-args) sound like they could be useful. Because the setup code could take a while to execute it's also necessary to wait for the code to finish before running the main page which complicates things, not sure on the best approach.

**Comment by stereobooster** [comment]
I do understand your motivation, but I do not expect that much code in `snapSaveState`, so win in size will be really small. If you find yourself in situation when you need to add a lot of code to this function we can address this issue explicitly.

Also need to say that there are cases when proposed solution (external code) will not work. FOr example, Redux case, which needs reference to the store:

```js
const store = createStore(counterApp, preloadedState || initialState)
window.snapSaveState = () => ({
  "__PRELOADED_STATE__": store.getState()
});
```

this means that I will need to support existing solution and proposed solution. Taking into account state of the project and time which I can dedicate to support it - this feature is not likely to happen any time soon. I will close this ticket (at least for now).

**Comment by MaxMilton** [comment]
Thanks for the reply and putting in the extra details. I can definitely appreciate having limited time for these kinds of projects, my time gets smashed too when I work on consulting projects. When it comes to performance it's easy to sink a lot of time so I really thank you for putting in the effort to put `react-snap` together and maintain it.

The ability to run arbitrary JS could increase the maintenance workload since it's likely users will run into bugs and be confused if they should report the issue to react-snap or puppeteer etc.

I might have a play with this idea and see if I can come up with some compile time hooks. My current thinking is to check if a file e.g. `reactsnap.before.js` or `reactsnap.after.js` exists and automatically eval it at render time. That way it comes in line (a little) with the projects "zero configuration" idea.

If I make any progress worth sharing I'll report back here.
