### ISSUE TITLE
Bug: graceful shutdown doesn't work

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#15]
It should clean up all resource (e.g. close browser and server) instead of failing if user interrupts execution with `Ctrl + C`

**Comment by M-ZubairAhmed** [comment]
Hi @stereobooster can you specify me or guide me to solve this issue?

**Comment by stereobooster** [comment]
1. start react-snap and it is lengthy process
2. interrupt execution with Ctrl + C
3. Expected behaviour it will finish current jobs, skip the rest, shutdown browser and internal server. Instead it prints some error.

Here is the conde responsible for functionality

```js
process.on("SIGINT", () => {
    if (shuttingDown) {
      process.exit();
    } else {
      shuttingDown = true;
      console.log(
        "Gracefully shutting down. To exit immediately, press ^C again"
      );
    }
  });
```

**Comment by stereobooster** [comment]
I walked through it again, this is complicated for the first issues. I was too optimistic
