### ISSUE TITLE
async on main.js script tag

### ISSUE THREAD

**Issue by hesedel** [stereobooster/react-snap#151]
Can we add an async to the main.js script tag? I thought one of the main points of generating static pages is to be able to immediately see the page without having to wait for the render-blocking script to load, which in React's case, is big.

**Comment by stereobooster** [comment]
>  I thought one of the main points of generating static pages is to be able to immediately see the page

This metric is called First Paint and it improves if you have HTML prerendered. Browser can start render HTML as soon as all HTML and CSS available. Browser does not need to wait for JS to be downloaded unless JS tag is in the top of document (`main.js` is typically in the end of document).

There is also Time To Interactive metric. The only way to improve this metric is by reducing size of JS or by using HTTP2 push.

Async doesn't really help see [Round 7: load JS in a non-blocking manner](https://github.com/stereobooster/react-snap/blob/master/doc/an-almost-static-stack-optimization.md#round-7-load-js-in-a-non-blocking-manner)

**Comment by hesedel** [comment]
Thank you for getting back so fast. It did seem to be delaying the First Paint when I tried on Chrome and throttling the network. But thanks for the link. I found my answer there: `"asyncScriptTags": true`.

**Comment by stereobooster** [comment]
> It did seem to be delaying the First Paint when I tried on Chrome and throttling the network

If you can provide reproducible example I can take a look. Maybe I miss something

**Comment by hesedel** [comment]
Sure, will do when I get home from work later. 👍

**Comment by hesedel** [comment]
[async.zip](https://github.com/stereobooster/react-snap/files/1834436/async.zip)
here's a zip of a video. async is the left side

**Comment by stereobooster** [comment]
This happens because css file downloaded after JS - this is the issue you need to fix.

**Comment by hesedel** [comment]
You're right. Seems to have been a fluke. I ran it again, almost no difference. Thanks for you time.
