### ISSUE TITLE
[css-in-js] Css display: flex omitted from the inline style declaration

### ISSUE THREAD

**Issue by mnemanja** [stereobooster/react-snap#16]
Hi there.

I'm having a create-react-app with material-ui, and their components are inlining their css already. I've noticed that the property "display: flex" has been removed in the built version that runs with react-snap right now.

Is this an expected behavior?

**Comment by stereobooster** [comment]
> Is this an expected behavior?

Nope. Do you have small example to reproduce this issue. 

"inlining", in case of React components, can have different meanings. If it is CSS bundle in components with something like browserify, then you will have 2 copies of CSS. One in rendered HTML and one in JS. There is `removeStyleTags` config to remove rendered style tags, if this the case.

**Comment by stereobooster** [comment]
Or in case you are using `inlineCss: true` option, it can be a bug in `minimalcss` library. Would be much easier to debug with small example.

**Comment by stereobooster** [comment]
Feel free to reopen when you will have more details
