### ISSUE TITLE
How does pre-render work in create-react-app?

### ISSUE THREAD

**Issue by vKongv** [stereobooster/react-snap#163]
Hi I tried the steps in the readme to add `react-snap` to pre-render my page by adding `"postbuild": "react-snap"` into my package.json. I then run `yarn run build` and upload the `build` file into s3 for hosting.

My question is how do I know that it is working? I try view my page source but the meta tag is still not populating. Sorry for being a noob here.

**Comment by stereobooster** [comment]
if you see something like this

```
yarn build
...
🕸  (1/2) /404.html
🕸  (2/2) /
```

it means it is working. Also open html files before and after and compare. Or you can add to `package.json`

```
  "reactSnap": {
    "headless": false
  }
```

and you will be able to see window of chrome

**Comment by vKongv** [comment]
Hey @stereobooster, thanks for your quick reply and it is really helpful! Unfortunately my site involve dynamic data that will change frequently (like list of product) that cannot be pre-render and store as a html file in the build folder upfront. Do you have any recommendation for handling this kind of problem of pre-rendering? Basically what I need is to allow FB share button to read my product details through `meta` tag when the user share it.

**Comment by stereobooster** [comment]
Maybe ["SEO-only server prerenderers"](https://github.com/stereobooster/react-snap/blob/master/doc/alternatives.md#seo-only-server-prerenderers) is what you looking for? Or SSR?

Also you can skip generating dynamic content by detecting `react-snap`: 

```js
if (navigator.userAgent === 'ReactSnap') {
  // blank page
} else {
  // content
}
```

**Comment by vKongv** [comment]
Yeah, I am looking on the pre-render solution. Thanks for your help! @stereobooster
