### ISSUE TITLE
inlineCss: true will deactivate fixWebpackChunksIssue: true

### ISSUE THREAD

**Issue by aheissenberger** [stereobooster/react-snap#17]
it is not possible to use both at the same time with react-snap: "0.6.2"

**Comment by stereobooster** [comment]
can you provide an example? I see no issues with code

**Comment by stereobooster** [comment]
Don't bother I got example

**Comment by stereobooster** [comment]
Resolved in 0.7.0

**Comment by stereobooster** [comment]
@aheissenberger if you are using `inlineCss`, do you have traces? How much performance improves for you? Use webpagetest.org for traces, select android and average 3G.

**Comment by aheissenberger** [comment]
my current test page has no relevant amount of css but I will provide you with more facts after finishing the project
