### ISSUE TITLE
React Router Links

### ISSUE THREAD

**Issue by hipstersmoothie** [stereobooster/react-snap#189]
Everything works pretty well, all my routes are indeed rendered as .html files. Where I'm running into problems:

* My react router `Link`s require this format for linking:

```
<Link to='/some/path.html' />
```

But after my static pages are rendered, the anchors link to a non-existant files. I would like for the link to link to the correct page. When at the the root file removeing the leading slash works. And when nested, the path must be a relative path to the file.

How would you suggest solving this? Is this library compatible with react-router? Do i have to write code to transform the HREFs into working links?

* Same thing for images. My paths are slightly off

**Comment by stereobooster** [comment]
As far as I understood your main issue is relative paths. Relative paths are not supported at the moment, to change this we need to add resolution of relative paths to the [`addToQueue`](https://github.com/stereobooster/react-snap/blob/71a152ed02da2c083f148e94ff13bada7fb5aa73/src/puppeteer_utils.js#L130-L141) function.

Not sure I understood issue with images. Can you provide reproducible example?

**Comment by hipstersmoothie** [comment]
Image issue was due to me just viewing the .html files in chrome. Using something to serve the files fixes my image and CSS issues.

**Comment by akki47kishore** [comment]
Hi,
I was trying out react-snap for the first time and I was using React Routing for the routing, but apparently there is some issue. But it works perfecly in the development environment with yarn start. But when in the build environment, there is some issue.
Can you help me with this
