### ISSUE TITLE
How to run this postbuild if we are running build into node service with process_child

### ISSUE THREAD

**Issue by esuarezz** [stereobooster/react-snap#190]
Hi!
I am running this in my code:
     spawn.spawnSync('yarn', ['build'], {stdio: 'inherit'})

So react snap is on:
    "postbuild": "react-snap",

So, after the build we will do the post build, its fine, the issue is, I get an exception;
/bin/sh: 1: react-snap: not found
error Command failed with exit code 127.

**Comment by stereobooster** [comment]
can you run `yarn react-snap` in your shell? If yes then the issue with `spawn.spawnSync` if not, then something is wrong with npm modules, try 'rm -rf node_modules && yarn'

**Comment by stereobooster** [comment]
I guess I answered the question. If not, please reopen
