### ISSUE TITLE
Crawling of subpages skips them?

### ISSUE THREAD

**Issue by mikaelvesavuori** [stereobooster/react-snap#191]
Hi, and thanks for a great project!

The crawling of subpages isn't working for me – I just get react-snap skipping them?

Using the `include` field works fine, but isn't really maintainable for an unknown number of subpages, and especially since this one client has hundreds of products.

![reactsnap](https://user-images.githubusercontent.com/23580994/41152910-66256838-6b15-11e8-84fc-49929184cc0e.png)

```js
"reactSnap": {
	"source": "dist",
	"publicPath": "/",
	"crawl": true,
	"include": [
		"/index.html",
		"/products",
		"/press"
	]
}
```

Am I missing something?

**Comment by stereobooster** [comment]
It skips crawling, when it gets first error. Scroll your log up and find an error

**Comment by mikaelvesavuori** [comment]
Thanks, this was indeed the case. I keep getting stacks of `400` errors from Contentful, though when I hack the source code for react-snap, making it not skip stuff, the output sites look entirely correct?

We can probably close this question, however I am interested in why the false positives. Same for Hotjar which I'd rather skip for snapshotting.

**Comment by stereobooster** [comment]
there should be an error somewhere with stack trace, fix it and react-snap will work as expected. The issue is that react-snap can not tell if the error critical (whole website broken) or it is something minor so it panics on any error.
