### ISSUE TITLE
Unhandled promise rejection: Error: only absolute urls are supported

### ISSUE THREAD

**Issue by avkonst** [stereobooster/react-snap#195]
### If you are reporting a bug

I am not sure if it is a bug, but it seems it is as it is unhandled exception thrown to the console.

I tried react-snap for my react app and it fails with the following log. How could I troubleshoot and fix it?

```
> react-snap

(node:14480) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: only absolute urls are supported
(node:14480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✏️  / log: {}
✏️  / log:
✏️  / log:
✏️  / log:
✏️  / log:
✏️  / log:
✏️  / log:
✏️  / log:
✏️  / log:
🕸  (1/1) /

```

**Comment by stereobooster** [comment]
Yes looks like a bug - puppeteer complains about URL. Can you post reproducible demo?

**Comment by avkonst** [comment]
I could share static assets which you can run with 'serve'. Would it be
good enough?

**Comment by avkonst** [comment]
[build.zip](https://github.com/stereobooster/react-snap/files/2108866/build.zip)
You can serve this content and run react-snap against it. It is the state of the directory after react-snap failed. Remove 200 file to make it runnable again.

**Comment by avkonst** [comment]
thanks!

**Comment by stereobooster** [comment]
I can not reproduce it. This is what I see.

```
yarn react-snap
🔥  / pageerror:

✏️  / log: {}
🕸  (1/1) /
```

I can push my reproducible demo, so you can check it

**Comment by stereobooster** [comment]
try v1.13.1

**Comment by MacKentoch** [comment]
Just updated to `1.15.0` and I confirm issue is gone ✌️

I had then a *clear to understand* issue with firebase `onAuthStateChanged` event that I just escaped for react-snap and all went well:
```javascript
    const snap = navigator.userAgent === 'ReactSnap';

    if (!snap) {
      auth.onAuthStateChanged(this.handlesOnAuthStateChange);
    }
```

Thank you @stereobooster !
