### ISSUE TITLE
cacheAjaxRequests window.snapStore only of first crawled page

### ISSUE THREAD

**Issue by hesedel** [stereobooster/react-snap#197]
It seems that window.snapstore is only available on the first crawled page. Is this how it is supposed to be? Or is something wrong with my setup?

**Comment by hesedel** [comment]
I'm loading data for the main navigation, so i was hoping to cache this so that the nav is immediately available and just updated with ajax if anything changed after the build. And so I was hoping to use the data stored in `snapStore` so that the component could immediately display it.

I was hoping to achieve this with any page initially accessed.

**Comment by stereobooster** [comment]
What you described is supported. If you have problems with it post reproducible demo of the error

**Comment by hesedel** [comment]
Just to clarify how the crawler works, the crawler also just clicks on the link and if the link is, for example, loaded via react-router, then the component is already loaded and doesn't execute the `componentDidLoad` which calls the ajax request?

**Comment by stereobooster** [comment]
It is not clicking to URLs, it loads each url by navigating browser to it. React in the browser works as expected, everything called appropriately. You can add `console.log` to any callback (like `componentDidLoad`) to see if it is called or not or what it returns

**Comment by hesedel** [comment]
The ajax call seems to be working on every page crawl. I'll fork my repo and share it with you, if it's okay and would probably make things easier. I also have an unrelated issue where react-snap is causing an error when I execute `yarn test` and it's gone when I `yarn remove react-snap`

**Comment by hesedel** [comment]
Oh okay so it was the serviceworker? I wouldn’t expect that as i see in chrome console that service worker cannot be installed because localhost is not on an https protocol unless react-snap is able to.

So for now my actionable point would be your last suggestion?

Thank you

**Comment by stereobooster** [comment]
I thought it was service worker, but appears it is browser cache. I'm preparing fix

**Comment by stereobooster** [comment]
Fixed in v1.14.0. you need to add `"puppeteer": { "cache": false }` in the reactSnap config

**Comment by hesedel** [comment]
Cool! Thanks! Cheers!
