### ISSUE TITLE
`fixWebpackChunksIssue` broken in latest react-scripts (webpack 4)

### ISSUE THREAD

**Issue by barlock** [stereobooster/react-snap#201]
The newest release of react-scripts (`2.0.0-next.3e165448`) upgrades to webpack 4. With this comes multiple chunks by default:

* runtime~main.34d053e1.js
* vendors.e8add2cc.chunk.js
* main.65029f23.chunk.js

All of these seem to need to be included as `<script>` tags and not just preloaded. I haven't dug into why yet but I believe the [regex](https://github.com/stereobooster/react-snap/blob/master/index.js#L365) (`mainRegexp`) to keep in a script tag should be updated to include these three. I can create a PR if you think that seems like a valid solution. 

A workaround currently is to disable `fixWebpackChunksIssue`.

**Comment by stereobooster** [comment]
Need to investigate how to fix it better. Thanks

**Comment by mdugue** [comment]
any news on this?

**Comment by stereobooster** [comment]
Fixed in v1.19.0
