### ISSUE TITLE
Fails to run at ubuntu server

### ISSUE THREAD

**Issue by yantakus** [stereobooster/react-snap#202]
```
> react-snap

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lift-ui@2.0.0 react-snap: `react-snap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lift-ui@2.0.0 react-snap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-20T11_33_31_081Z-debug.log
```

contents of the above mentioned log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'react-snap' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose run-script [ 'prereact-snap', 'react-snap', 'postreact-snap' ]
5 info lifecycle lift-ui@2.0.0~prereact-snap: lift-ui@2.0.0
6 info lifecycle lift-ui@2.0.0~react-snap: lift-ui@2.0.0
7 verbose lifecycle lift-ui@2.0.0~react-snap: unsafe-perm in lifecycle true
8 verbose lifecycle lift-ui@2.0.0~react-snap: PATH: /root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/lift/lift-ui/node_modules/.bi$
9 verbose lifecycle lift-ui@2.0.0~react-snap: CWD: /lift/lift-ui
10 silly lifecycle lift-ui@2.0.0~react-snap: Args: [ '-c', 'react-snap' ]
11 silly lifecycle lift-ui@2.0.0~react-snap: Returned: code: 1  signal: null
12 info lifecycle lift-ui@2.0.0~react-snap: Failed to exec react-snap script
13 verbose stack Error: lift-ui@2.0.0 react-snap: `react-snap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid lift-ui@2.0.0
15 verbose cwd /lift/lift-ui
16 verbose Linux 4.4.0-127-generic
17 verbose argv "/root/.nvm/versions/node/v8.11.3/bin/node" "/root/.nvm/versions/node/v8.11.3/bin/npm" "run" "react-snap"
18 verbose node v8.11.3
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error lift-ui@2.0.0 react-snap: `react-snap`
22 error Exit status 1
23 error Failed at the lift-ui@2.0.0 react-snap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

The problem is it works fine for me at my mac, but when I push it to ubuntu server, it fails with the above mentioned error. Any ideas?

```
root@DT1:/lift/lift-ui# node -v
v8.11.3
```

```
"react-snap": "^1.15.0",
```

**Comment by stereobooster** [comment]
I run react-snap in Travis (which is Ubuntu). I'm pretty sure issue is with your setup. Maybe you forgot to run `npm i`. Can you post reproducible demo?

**Comment by manoj-makkuboy** [comment]
`18 info lifecycle stanza@0.1.0~postbuild: Failed to exec postbuild script
19 verbose stack Error: stanza@0.1.0 postbuild: `react-snap`
19 verbose stack Exit status 1
19 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
19 verbose stack     at emitTwo (events.js:126:13)
19 verbose stack     at EventEmitter.emit (events.js:214:7)
19 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
19 verbose stack     at emitTwo (events.js:126:13)
19 verbose stack     at ChildProcess.emit (events.js:214:7)
19 verbose stack     at maybeClose (internal/child_process.js:925:16)
19 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
20 verbose pkgid stanza@0.1.0
21 verbose cwd /var/www/sl__tech_repo/stanza
22 verbose Linux 4.4.0-1061-aws
23 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
24 verbose node v8.11.3
25 verbose npm  v5.6.0
26 error code ELIFECYCLE
27 error errno 1
28 error stanza@0.1.0 postbuild: `react-snap`
28 error Exit status 1
29 error Failed at the stanza@0.1.0 postbuild script.
29 error This is probably not a problem with npm. There is likely additional logging output above.
30 verbose exit [ 1, true ]`

The same as @yantakus Running fine in mac but failing in ubuntu aws box

**Comment by stereobooster** [comment]
Are you able to install puppeteer in linux in first place? https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by jmikrut** [comment]
I am currently experiencing the same issues on Ubuntu 16.04 but on a DigitalOcean box.  Thought I'd +1.

**Comment by jmikrut** [comment]
Update - I just fixed this on my end.  I did two things:  installed swap space on my droplet, suspecting that `npm` was simply running out of memory, and then I double-checked all the permissions in my project.

Works now!

**Comment by manoj-makkuboy** [comment]
My bad, I assumed that puppeteer will install all ubuntu dependencies, but it didn't. Had to install from here https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md the ubuntu dependencies. Thanks @stereobooster
