### ISSUE TITLE
What URL is being used when react-snap opens in the headless browser?

### ISSUE THREAD

**Issue by hesedel** [stereobooster/react-snap#215]
Hello!

I need to specify a PUBLIC_URL for react to run on. And this messes up when running react-snap the files being crawled don't exist yet on the public url right after the build.

I am thinking of just using the URL used by react-snap when running it, and then replace instances of that url on the produced files. Or maybe there is a better solution to it?

As to why I need it: I need to load the react app on another URL and they need to be fetching the resources from the original URL.

Thanks in advance.

**Comment by hesedel** [comment]
Actually, this seemed to work: `http://localhost:45678/`

**Comment by stereobooster** [comment]
I didn't understand what was this about, but I guess it is resolved. Feel free to reopen.
