### ISSUE TITLE
Rendering 'index.html' file for routes

### ISSUE THREAD

**Issue by lewisdonovan** [stereobooster/react-snap#22]
I've noticed the static files for my routes are `/ROUTE.html` as opposed to `/ROUTE/index.html`. Is there any way I can change this?

**Comment by stereobooster** [comment]
use `/ROUTE/`

**Comment by lewisdonovan** [comment]
Thanks for the quick response. Would I add this to the `<Link>` elements? So like `<Link to={/ROUTE/} ... />`? Also, would this work with sub-routes, eg: `<Link to={/ROUTE/SUBROUTE/} ... />`? Cheers.

**Comment by stereobooster** [comment]
anything that ends with `/` will produce `/index.html`

**Comment by lewisdonovan** [comment]
Excellent, thank you.

**Comment by stereobooster** [comment]
I will leave this open, because I suppose this will be asked a lot. Options to solve: 
1. mention this is in FAQ
2. always generate `/index.html`

**Comment by lewisdonovan** [comment]
Yeah, good call. I think adding that in the Readme.md would save time for both you and users ;)

**Comment by stereobooster** [comment]
I created another ticket for this
