### ISSUE TITLE
Supporting updated React Context API

### ISSUE THREAD

**Issue by harrysolovay** [stereobooster/react-snap#223]
I'm not reporting a bug––I just have a question (potentially a bad one, but here it goes):

I'm trying to build a static site that uses [React's updated Context API](https://reactjs.org/docs/context.html). React Snap seems like a really, really nice solution––it has fewer opinions than other static site generation libraries; you build your project the way you like, and tack on the react-snap build script (beautiful!). Still, there's a lot I don't know about compromises that one makes when opting into this build tool. My main concern is that I don't know if react-snap plays well with the Context API. Down the line, how could I make sure that state (from every provider) is persisted between pages?

Thank you for taking the time to read this through & please let me know if you have any questions.

Kind regards,

Harry

**Comment by harrysolovay** [comment]
Thank you for such a speedy reply 👍 

I'm hazy on the details of how react-snap works. Having the HTML pre-rendered in a static build means that there's no need for the loading of irrelevant components, styles and data (which results in faster load times). But, when possible, does the full JS bundle get loaded in? If not, how is it that the generated static pages communicate with other pages and JS counterparts? And is this something I should be weary of? I lack a complete understanding of the internals of react-snap and want to make sure there are no gotchas that I should know about. I hope that isn't too vague. And thank you again for the support.

**Comment by stereobooster** [comment]
Let's assume you have simplest SPA

```
index.html (empty html, which will load js and css)
index.css
index.js (all our application code, maybe React or Vue or Angular etc)
```

Let's see how it loads

```
--- html ---
           --- css ---
           --- js  ---
                      --- js parsed and html rendered ---
                                                         --- html rendered by browser ---
                                                                                        ^
                                                  user can see content and can interact | 
```

Now let's see how app looks like after reactSnap

```
index.html (prerendered html, with critical css inlined)
index.css (the same as original)
index.js (the same as original)
```

Let's see how it loads

```
--- html ---
           --- html rendered by browser ---
                                          ^
                     user can see content | 
           --- css ---
           --- js  ---
                      --- js parsed and html rendered ---
                                                         
                                                        ^
                                  user can can interact | 
```

This is the basic idea, there are also cases with AJAX requests and some nuances. reactSnap only prererenders html and nothing else. It is up to you how do you split JS, or how you load data.

**Comment by harrysolovay** [comment]
Fantastic! I've been messing around with it for the past few hours and it's BEAUTIFUL! I already like it far more than Phenomic or Gatsby. Thank you for the support!

**Comment by stereobooster** [comment]
There is also https://github.com/stereobooster/react-snap/blob/master/doc/anatomy-of-js-static-website-generator.md and other articles in docs folder. Tell me what you think about it. Will close it, because it is resolved.

**Comment by harrysolovay** [comment]
Thank you for the resources! I finally understand what's happening under the hood.
