### ISSUE TITLE
How is it search engine friendly?

### ISSUE THREAD

**Issue by ri8ika** [stereobooster/react-snap#228]
Hi,

Thanks for the react-snap. I loved it very much.

I wanted to know how is it search engine friendly? I saw in the README.md that it is made for SEO:

`Enables SEO (google, duckduckgo...) and SMO (twitter, facebook...) for SPA.`

But I couldn't see any meta tags added when I build the project. Can you please describe?

Or, do I need to use react-helmet?

Thanks again,
Bhojendra

**Comment by stereobooster** [comment]
> Enables SEO 

Means it prerenders HTML, so search engine sees some content instead of blank page. But if you want some custom meta tags [you need to use `react-helmet`](https://github.com/stereobooster/an-almost-static-stack/blob/react-snap/src/components/Seo.js).

**Comment by ri8ika** [comment]
Thanks.
