### ISSUE TITLE
Standalone React applications

### ISSUE THREAD

**Issue by akuji1993** [stereobooster/react-snap#231]
I have spent most of today and yesterday trying to get react-snap running in a standalone React application that hasn't been created with create-react-app. Sad to say, I'm apparently doing something wrong, since it just doesn't output anything on the site now, just an empty `<div id="root"/>` 

I'd be really happy, if you would include a documentation regarding adding it to those projects, since we never use create-react-app as a base for our projects (too much stuff to do with the webpack.config and honestly, CRA just clutters a lot of stuff into your project that you don't need). 

If documentation is too much of a hassle, which I get, can you provide any example on how to get this running in a normal React app? That would be really awesome.

**Comment by akuji1993** [comment]
Here you go https://github.com/akuji1993/standalone-react-snap-example

**Comment by akuji1993** [comment]
On https://github.com/akuji1993/standalone-react-snap-example/tree/introduce-react-snap you can find my try of integrating react-snap into the project, which results in the content being snapped and loaded, but the javascript is never served, therefore, for example, my buttons don't work on press and no JS content is executed.

**Comment by stereobooster** [comment]
Here you go https://github.com/akuji1993/standalone-react-snap-example/pull/1

**Comment by akuji1993** [comment]
Yeah, the setup I've sent you now renders the components, but the JS scripts are completely missing and aren't loaded. Sorry if my first description was unclear or misled you.

**Comment by akuji1993** [comment]
Hm, wait, the branch that you made on your fork, that is base to your PR, that is actually running fine for me. You made it work! Even though your code looks almost exactly like what I did. When I `serve` the content of dist, there's still all the interaction on the page. (Check my repo, I pushed one more commit that your fork doesn't have yet, so you can easily serve dist).

**Comment by akuji1993** [comment]
Hm, wait, the example you provided in your fork / PR actually works fine. The only problem I see is this: 

![image](https://user-images.githubusercontent.com/7081514/43591127-e23f84d4-9672-11e8-90c0-f4a7a7e31d9d.png)

There's all the JS code loaded immediately. I got the feeling I just misunderstand something about this.

**Comment by stereobooster** [comment]
There is a text of `index.html`, there are not `<script>` tag. Maybe you see it in `200.html`, but this is different thing, this is original `index.html`

**Comment by akuji1993** [comment]
Ah sorry, my mistake was that i still ran `npm run build` on accident and in that case, it of course worked, because just no prerendering happening 🤦‍♂️  

With your `npm run prerender` command, indeed it is not working...

**Comment by stereobooster** [comment]
hey @akuji1993 you have the same problem as in https://github.com/stereobooster/react-snap/issues/348#issuecomment-483069792

```diff
    <body>
-        <div id="root"/>
+        <div id="root"></div>
    </body>
```
