### ISSUE TITLE
bug in render dynamic url

### ISSUE THREAD

**Issue by uxitten** [stereobooster/react-snap#235]
i use react-router dom and i have a blog page with many post and all post have a slug for link to details post but has a bug in react-snap when build page

<img width="325" alt="screen shot 2018-08-08 at 12 03 30 pm" src="https://user-images.githubusercontent.com/1549069/43823075-30f28f10-9b03-11e8-8084-636cf40344eb.png">

**Comment by stereobooster** [comment]
It means that you really have URL's like this. React-snap itself doesn't know anything about react or react-router. It scans html of pages for `<a href...>`. It means there are links with `/blog/:slug/` somewhere in your code.

**Comment by uxitten** [comment]
i fixed this bug in puppeteer_utils.js whit one line code

<img width="592" alt="screen shot 2018-08-08 at 1 01 00 pm" src="https://user-images.githubusercontent.com/1549069/43825892-2db82dde-9b0b-11e8-93ed-070d3348556b.png">

**Comment by stereobooster** [comment]
This is not a fix, you just hide bug. Links like this `<a href="blog/:slug"></a>` should not exist in first place.

**Comment by uxitten** [comment]
i have not /blog/:slug link, i definition /blog/:slug for react-router for dynamic url

and i used in blog page for determine dynamic link

<img width="427" alt="screen shot 2018-08-08 at 1 04 32 pm" src="https://user-images.githubusercontent.com/1549069/43826251-214216a4-9b0c-11e8-96f5-27bd9647ba25.png">

**Comment by stereobooster** [comment]
You can provide reproducible example if you want me to investigate this issue. But I can repeat what I said before, react-snap doesn't know anything about react or react-router (you can check source code), it works with html generated by browser. So if it finds link like `/blog/:url` it gets it from html

**Comment by uxitten** [comment]
thanks i find a bug 👍

**Comment by vijya76** [comment]
@uxitten Can you let me know how you resolved this issue?
I have route like `/:city` and another sub route like `/:city/about` and when I run react-snap it throws error `ENOTDIR`
