### ISSUE TITLE
Evaluation failed: Error: not in stylesheetAstObjects

### ISSUE THREAD

**Issue by iTonyYo** [stereobooster/react-snap#24]
![image](https://user-images.githubusercontent.com/5499703/32213369-e888e3c6-be55-11e7-87dc-f7157f0ace7a.png)

**I can access `[main.58623fc8.css](https://m.huso.io/static/css/main.58623fc8.css)`,**
![image](https://user-images.githubusercontent.com/5499703/32213608-df285586-be56-11e7-854c-5c20db1c554a.png)

**Here's my `.env.production` file,**
![image](https://user-images.githubusercontent.com/5499703/32213520-89a0b7ac-be56-11e7-8950-c54d5d47ff9f.png)

**Comment by stereobooster** [comment]
Error comes from https://github.com/peterbe/minimalcss/blob/master/src/run.js#L223. But I'm not sure how you got into this edge case. Can you provide minimal reproducible example.

**Comment by iTonyYo** [comment]
OK, I'll let u know, once the reproducible example is ready.

**Comment by iTonyYo** [comment]
@stereobooster OK, I'll let u know, once the reproducible example is ready.

**Comment by stereobooster** [comment]
Feel free to reopen when you will have more details

**Comment by stereobooster** [comment]
can be connected to this https://github.com/peterbe/minimalcss/issues/70
