### ISSUE TITLE
Check if react-snap / headless is running

### ISSUE THREAD

**Issue by onionhammer** [stereobooster/react-snap#245]
Hey, not sure if this is addressed and buried somewhere, but I wasn't able to find it..

I am loading a bing maps component when the page loads, and I want to skip the step of adding the <script> tag if it's react-snap's headless chrome running against the app. I've already added the 'skipThirdPartyRequests: true' setting, but the <script> tag is still being set.

I just want a condition like `if (!window.reactSnap) addScriptTag`

**Comment by stereobooster** [comment]
`if (navigator.userAgent !== 'ReactSnap') addScriptTag `

**Comment by onionhammer** [comment]
That did the trick - everything is working again!

I would recommend you add this to your docs - also maybe address using `preact` in your docs (sorry if this is a separate issue); which (seems) actually easier - you just add a 'root.firstElementChild` as your third argument to `render`.

Great tool!

**Comment by stereobooster** [comment]
@onionhammer can you tell me more about preact thing. I'm not very experienced with it. Is this snippet required to do proper rehydration?

**Comment by onionhammer** [comment]
@stereobooster I believe so? Hard to tell if it's actually working or not; but according to lighthouse over a second was shaved off the speed index.
