### ISSUE TITLE
Animate conditional rendering

### ISSUE THREAD

**Issue by b0gd4n** [stereobooster/react-snap#246]
I am trying to figure out the best way to animate 2 different elements that render conditionally on a prop, eg:

```
const AnimContainer1 = posed.div({
  exit: {opacity: 0},
  enter: {opacity: 1}
})
const AnimContainer2 = posed.div({
  exit: {opacity: 0},
  enter: {opacity: 1}
})
{this.props.condition ? (
  <AnimContainer1 pose={this.state.renderc1 ? 'enter' : 'exit'}>{container1contetent}</AnimContainer1>
) : (
  <AnimContainer2 pose={this.state.renderc2 ? 'enter' : 'exit'}>{container1contetent}</AnimContainer2>
)}
```
I tried having 2 different states for each element and pass it to the posed component. I am trying to change the state through a combination of react methods (componentDidMount, componentWillUnmount, componentWillReceiveProps) but it all feels very clumsy and `enter` animation is not working.

Also, I would like to animate the `content` of each component, so fade in/out when `container1content` changes.

**Comment by stereobooster** [comment]
Hi. I'm not sure how this connected to react-snap. If this is a general React question you can try to ask it at StackOverflow or React discussion group
