### ISSUE TITLE
Javascript not being executed after build 

### ISSUE THREAD

**Issue by KrisCoulson** [stereobooster/react-snap#251]
I currently have a create-react-app  that is not ejected. Our react app is pretty standard with a few dynamic imports at certain paths. After running the build script and react-snap post build the site gets compiled and looks great and can be easily navigated. 

The issue seems to be that none of the javascript works.

The homepage does not have any dynamic content just a header carousel but the images no longer rotate and we have a few accordions that no longer function.

Is there anything that we are doing wrong? Or an option that I am missing?

**Comment by stereobooster** [comment]
Did you check console in production, maybe JS is there it just some kind of error. Or HTML itself doesn't contain links to JS. If this is later option, please config of `react-snap` if any and version of create-react-app

**Comment by KrisCoulson** [comment]
Yeah, In production environment the js is being bundled and chunked and appears to be inserted as link with a preload attribute. 

No errors in console and 2  warnings that looked like so
> The resource [...] was preloaded using link preload but not used within a few seconds from the window's load event. [](url)

**Comment by stereobooster** [comment]
I'm not sure how I can help you here without actual example of the error.

**Comment by KrisCoulson** [comment]
Okay I will see if I can, work out a reproducible example.

**Comment by stereobooster** [comment]
I hope this is fixed in v1.19.0. If not feel free to reopen

**Comment by KrisCoulson** [comment]
Hey sorry I never got back to you after upgrading and running the build it seemed to work! Thank you for your support!
