### ISSUE TITLE
Just installing will build the static html automagically. It shouldn't!

### ISSUE THREAD

**Issue by hackhat** [stereobooster/react-snap#253]
I install the module.
Note that I don't do any other changes, I don't call react-snap.
I run my build, my files are run through react-snap.

Why? I want to configure something and tell to use this library. 

I think is a really bad pattern to run it automatically just because is installed. Should be called manually by the user.

**Comment by stereobooster** [comment]
It will not, it is something wrong with your `package.json`. You can post contents of your package.json and will show you the error

**Comment by hackhat** [comment]
Having `"postbuild-client": "react-snap",` will do the trick. Which is a random name I gave it.
