### ISSUE TITLE
how to rehydrate redux state

### ISSUE THREAD

**Issue by DonGiulio** [stereobooster/react-snap#265]
Hello, 

I didn't quite get how to use the `snapSaveState` with rehydrating redux state. Would it be possible to make an example or to improve the readme section? 

I'm really quite confused. 

Thanks,

**Comment by stereobooster** [comment]
https://github.com/stereobooster/react-snap#redux

```js
// Grab the state from a global variable injected into the server-generated HTML
const preloadedState = window.__PRELOADED_STATE__;

// Allow the passed state to be garbage-collected
delete window.__PRELOADED_STATE__;

// Create Redux store with initial state
const store = createStore(counterApp, preloadedState || initialState);

// Tell react-snap how to save Redux state
window.snapSaveState = () => ({
  __PRELOADED_STATE__: store.getState()
});
```

what exact line you don't understand?

**Comment by DonGiulio** [comment]
I don't understand the need for 

```
window.snapSaveState = () => ({
  __PRELOADED_STATE__: store.getState()
});
```

Isn't it sufficient to just follow the [redux](https://redux.js.org/recipes/serverrendering) tutorial?

**Comment by stereobooster** [comment]
this is react-snap specific callback, it is needed if you want that generated HTML would contain this data. Everything else is basically copy-pasted from tutorial.

**Comment by stereobooster** [comment]
I guess, I answered your question. Feel free to re-open

**Comment by DonGiulio** [comment]
Sorry, was busy for a while.

I figured by checking [the code](https://github.com/stereobooster/react-snap/blob/98f44c8ee5fd42d83f08f53611571148e86a5888/index.js#L645) that the react-snap calls `snapSaveState` at some point and saves its content in a `<script>` tag in the rendered page. 

I'm still not clear of when this is called, need to dig deeper into `page.evaluate`

I still didn't get `react-snap` to work on my project, I'm guessing the trouble is to do with the redux store. 

I'm guessing though that the `snapSaveState` should be somewhere else than the `window.preloadedState` stuff. 

I'm trying now to create my store with: 

```
const store = railsProps => {
  const preloadedState = window.__PRELOADED_STATE__;
  delete window.__PRELOADED_STATE__;

  return createStore(
    rootReducer,
    railsProps || preloadedState,
    composeEnhancers(applyMiddleware(thunkMiddleware))
  );
};
```

and defining `snapSaveState` right after initialising the store: 

```
const store = configureStore(props);
window.snapSaveState = () => ({
    __PRELOADED_STATE__: store.getState()
  });
return (
    <Provider store={store}>
      <BrowserRouter>
        <ThemeProvider theme={theme}>
          <Switch>
            <Route path="*" component={App} />
          </Switch>
        </ThemeProvider>
      </BrowserRouter>
    </Provider>
  );
```

As mentioned this it not working still, my routes that show data from the store are all rendered just as empty pages.

I think that might be of help to everyone to explain more in depth how this should be used.

**Comment by DonGiulio** [comment]
I'm also not sure whether I will need `frontLoad` so that react-snap will wait until the data is loaded from my json backend into my redux store. will I?

**Comment by stereobooster** [comment]
> As mentioned this it not working still, my routes that show data from the store are all rendered just as empty pages.

Are you sure you have issue with Redux? I would assume that issue is with something else. 

If you use react-snap put of the box, and don't touch redux it will render pages, but later there will be blink of the white screen. If you don't even see correctly rendered pages in first place this is not Redux this is something else.

**Comment by DonGiulio** [comment]
mmh... spot on, indeed the problem wasn't redux, but a couple of routes that were `development` only, but `npm run-script build` sets the ENV to `production` without chances to override. 

Now I get a bunch of html files in the build directory, if I load them from disk I see the pages as they should look like, but react is not active. 

in the console I see a bunch of: 

```
main.243dafd1.chunk.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
1.7fa6f976.chunk.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/static/css/1.c05484ac.chunk.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/static/css/main.6e0104d4.chunk.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/favicon.ico:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
The resource file:///static/js/1.7fa6f976.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I'm not sure if this is expected? I guess I should rather visit these urls passing through a server? how can I do that in dev?

**Comment by stereobooster** [comment]
This is webpack-chunk issue what config do you use? If CRA2 it is known issue https://github.com/stereobooster/react-snap/issues/264

**Comment by DonGiulio** [comment]
yep, that's it, I have CRA2. 

```
"reactSnap": {
  "fixWebpackChunksIssue": false
}
```

doesn't seem to help tho

**Comment by stereobooster** [comment]
Actually how do you serve your build? Try from the root of the project

```
npx serve -s build
```

**Comment by BriantAnthony** [comment]
> Sorry, was busy for a while.
> 
> I figured by checking [the code](https://github.com/stereobooster/react-snap/blob/98f44c8ee5fd42d83f08f53611571148e86a5888/index.js#L645) that the react-snap calls `snapSaveState` at some point and saves its content in a `<script>` tag in the rendered page.
> 
> I'm still not clear of when this is called, need to dig deeper into `page.evaluate`
> 
> I still didn't get `react-snap` to work on my project, I'm guessing the trouble is to do with the redux store.
> 
> I'm guessing though that the `snapSaveState` should be somewhere else than the `window.preloadedState` stuff.
> 
> I'm trying now to create my store with:
> 
> ```
> const store = railsProps => {
>   const preloadedState = window.__PRELOADED_STATE__;
>   delete window.__PRELOADED_STATE__;
> 
>   return createStore(
>     rootReducer,
>     railsProps || preloadedState,
>     composeEnhancers(applyMiddleware(thunkMiddleware))
>   );
> };
> ```
> 
> and defining `snapSaveState` right after initialising the store:
> 
> ```
> const store = configureStore(props);
> window.snapSaveState = () => ({
>     __PRELOADED_STATE__: store.getState()
>   });
> return (
>     <Provider store={store}>
>       <BrowserRouter>
>         <ThemeProvider theme={theme}>
>           <Switch>
>             <Route path="*" component={App} />
>           </Switch>
>         </ThemeProvider>
>       </BrowserRouter>
>     </Provider>
>   );
> ```
> 
> As mentioned this it not working still, my routes that show data from the store are all rendered just as empty pages.
> 
> I think that might be of help to everyone to explain more in depth how this should be used.

For starters, I don't believe you setup your routes correctly. If "path" is set to "*", then any route will render an empty page.

You have to explicitly define each route and define what component will be rendered.

Ex:
<Route path="/" component={LandingPage} />
<Route path="/about-us" component={aboutUs}/>
