### ISSUE TITLE
Javascript not being executed after build of app created with create-react-app 2.0.4

### ISSUE THREAD

**Issue by GeordieP** [stereobooster/react-snap#266]
I believe I'm experiencing an issue similar to #251. Using the latest version of create-react-app and react-snap, none of the JS on the page seems to work.

Versions:
**react**: 16.5.2
**react-scripts**: 2.0.4
**react-snap**: 1.19.0

No custom options provided to react-snap or CRA; both running straight out of the box.

Reproduction repository here; React app with simple JS actions:
https://gitlab.com/GeordieP/snap-issue-cra

Similarly to #251, the JS appears to be bundled and chunked correctly, and is referenced in a script tag in the page. Tested on both Ubuntu 18.04 and macOS 10.14.

In addition, I've got the same app built with Parcel (v1.10.1) instead of CRA & webpack, and everything seems to work correctly:
https://gitlab.com/GeordieP/snap-issue-parcel/

I'd go ahead and use Parcel, but I run into a different problem when introducing async components:
https://gitlab.com/GeordieP/snap-issue-parcel-codesplit
... but that's for a separate issue. 😉

**Comment by dj-hedgehog** [comment]
I am experiencing the same issue since upgrading to CRA 2.x.

**Comment by stereobooster** [comment]
For now I will gather all CRA2 issues in this ticket https://github.com/stereobooster/react-snap/issues/264

**Comment by sanvyx** [comment]
Same issue.
 "react-scripts": "2.0.4"
 "react-snap": "1.19.0"

**Comment by sanvyx** [comment]
Solution
[#264](https://github.com/stereobooster/react-snap/issues/264#issuecomment-427370514)

It has some drawbacks, but it worked for me.
