### ISSUE TITLE
How to avoid flash/blink after loading content to state ?

### ISSUE THREAD

**Issue by GautierT** [stereobooster/react-snap#269]
Hi,
I'm building some landing page using Contentful (a content provider).
Content is loaded using axios and added to the state (this.setState). During this time there is a message displayed (Loading...). Once it's in the state i'm replacing the loading message with the content.

The pages are correctly  generated using react-snap. But there is a small flash displaying the "loading...." message when the content is hydrated. 

Is it possible to detect that there is already some content to disable the "loading" message ? Or any other way to prevent this effect ?

You can see the behavior here (slow down your browser to better see the effect) : https://www.seeuletter.com/landing/glissez-deposez/

Thanks for this awesome module !

**Comment by stereobooster** [comment]
There is `cacheAjaxRequests` config which will add content of the request to the global object, you can check if content is present and use it instead of fetching content again.

```
"reactSnap": {
  "cacheAjaxRequests": true
}
```

**Comment by GautierT** [comment]
Thanks. 
I tried but when i console.log on `window.snapStore` it's always undefined (in the constructor, componendDidMount and the function i use to fetch the content from Contentful...)

**Comment by GautierT** [comment]
To be clear @stereobooster it's request made to contentful domain. So not the "same domain" as you refer in the docs. Maybe it's the problem ?

**Comment by stereobooster** [comment]
Yes you totally right. Currently this works for the same domain. I guess you can tweak it to cache for your domain (you already forked it)

```
"reactSnap": {
  "cacheAjaxRequests": ["https://contenfull.com/"]
}
```

**Comment by stereobooster** [comment]
Also, take a look at this issue https://github.com/stereobooster/react-snap/issues/221. It is related to your situation too. You need to "fix" AJAX requests too, because otherwise API response can deviate from what is pre-rendered and users can get strange results, that is why `cacheAjaxRequests` is for the same domain only right now.

**Comment by GautierT** [comment]
Thanks. I will look into this.
I keep you posted.

**Comment by stereobooster** [comment]
It is possible to fork project and enable this in general, but I wouldn't do this feature without doing #221 first. Feel free to ask more questions if you need to
