### ISSUE TITLE
Issue with CSS after upgrading to CRA2

### ISSUE THREAD

**Issue by alan345** [stereobooster/react-snap#274]
Before upgrading to CRA2, it was working well.
Now. Css is not loaded correctly.
I have tried with and without option `"inlineCss": true`.
Here you have the result with `react-snap`:
![image](https://user-images.githubusercontent.com/15246526/47043320-33171e80-d142-11e8-9dd0-450142e0309b.png)
without `react-snap`:
![image](https://user-images.githubusercontent.com/15246526/47043336-3dd1b380-d142-11e8-934a-26814f80b6c7.png)
I am using:
`"react": "16.5.2"`
`"@material-ui/core": "3.2.0",`
Let me know if you have an idea how I can dig into this issue.
Thanks!

**Comment by stereobooster** [comment]
Can you post more info. Exact version of CRA and exact config of react-snap

**Comment by alan345** [comment]
yes sure: 
`"react-scripts": "2.0.5"`
` "react-snap": "^1.19.0",`

**Comment by alan345** [comment]
no I don't use `INLINE_RUNTIME_CHUNK=false`

**Comment by stereobooster** [comment]
You should use INLINE_RUNTIME_CHUNK=false with CRA2 until we get better solution

**Comment by alan345** [comment]
Same issue..
```
  "reactSnap": {
    "fixWebpackChunksIssue": false,
    "puppeteerIgnoreHTTPSErrors": true,
    "inlineCss": true,
    "INLINE_RUNTIME_CHUNK":false    
  },
```

**Comment by stereobooster** [comment]
try this

```sh
INLINE_RUNTIME_CHUNK=false yarn build
```

```json
"reactSnap": {
  "puppeteerIgnoreHTTPSErrors": true
}
```

**Comment by alan345** [comment]
also not working..

The behavior is weird, after I refresh, css is ok (static files), then I fire a query and then, css is not fully loaded:

https://j.gifs.com/rRLDX2.gif

**Comment by stereobooster** [comment]
I guess you have issue with JSS similar too https://github.com/stereobooster/react-snap/issues/99#issuecomment-355663842

**Comment by stereobooster** [comment]
Feel free to reopen, if you have more questions

**Comment by swoppy** [comment]
I have the same issue, I'm using CRA 3 with typescript and CSS Module. It messed up the layout, some HTML are even missing after this whole process.
