### ISSUE TITLE
Error with inlineCss 

### ISSUE THREAD

**Issue by nicolas-t** [stereobooster/react-snap#275]
Hello,

Thanks for your work ([I migrated from prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin/issues/131)) 

I've been using your library for a few month and it's working well.

Today I tried `inlineCss: true`
and got this error : 
```
error at /hello Error: Found stylesheets that failed to download (http://localhost:45678/assets/css/chunk-00a5.ac7f9236.css, 

...

at Object.minimalcss [as run] (/path/to/node_modules/minimalcss/src/run.js:420:11)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:182:7)
```

I'm working with vue.js and here is my config : 
```json 
  ...
  "reactSnap": {
    "source": "dist",
    "skipThirdPartyRequests": true,
    "inlineCss": true,
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ],
    "crawl": false,
    "include": [
      "/hello"
    ],
    "minifyHtml": {
      "collapseWhitespace": false,
      "removeComments": false
    }
  }
  ...
```

Did you already encounter this error ? Is there a simple workaround ? 

Thanks,

**Comment by stereobooster** [comment]
Haven't seen this one. Can you check if file which it tries to download is present in the `dist` folder or not.

**Comment by nicolas-t** [comment]
Yes they are present.
I think it's more of a `minimalcss` issue, so i've opened an issue there : 
https://github.com/peterbe/minimalcss/issues/274
