### ISSUE TITLE
Is there a way to make my application know that react snap is rendering the app?

### ISSUE THREAD

**Issue by GasimGasimzada** [stereobooster/react-snap#277]
I have a number of animations and intersection observers in one of my applications and I want to create snapshot using react-snap. However, I want all animations disabled; so, that I can have full page visible. Is there a way to inject a variable or something similar (e.g execute some form of JS) to react snap; so that I can disable animations?

**Comment by stereobooster** [comment]
```js
navigator.userAgent == "ReactSnap"
```

https://github.com/stereobooster/react-snap#useragent
