### ISSUE TITLE
Add flag to Chromium command

### ISSUE THREAD

**Issue by lewisdonovan** [stereobooster/react-snap#28]
Hiya,

The server environment I'm deploying to has security restrictions on running Chromium, so in order for react-snap to run correctly I'll need to add the `--no-sandbox` flag to Chromium when it runs. How would I go a bout doing that? Cheers.

**Comment by stereobooster** [comment]
need to expose this as option

```diff
  const browser = await puppeteer.launch({
    headless: options.headless,
+    args: ['--no-sandbox'] 
  });
```

**Comment by lewisdonovan** [comment]
Great, thanks again for the quick response.

**Comment by stereobooster** [comment]
There is also https://github.com/peterbe/minimalcss/issues/35, in case you are using `inlineCSS`

**Comment by stereobooster** [comment]
There is a PR for this merged, but haven't released package yet

**Comment by stereobooster** [comment]
v0.10.0

**Comment by Lemmih** [comment]
Thanks for the quick turnaround. React-snap is amazing and I love seeing SSR in my automated docker builds.

**Comment by lewisdonovan** [comment]
Excellent turn-around time. Much appreciated!
