### ISSUE TITLE
Handling IntersectionObserver 

### ISSUE THREAD

**Issue by thebuilder** [stereobooster/react-snap#285]
I'm curious if it's possible to control how `IntersectionObserver` is used doing the prerendering step.
It seems they are triggered (correctly) when they are inside the viewport, but this might be undesired behavior. If it should trigger an animation, you most likely don't want it to trigger before the client renders.

This is a problem if using `react-intersection-observer` [(see issue 132)](https://github.com/thebuilder/react-intersection-observer/issues/132).

Would a solution be to override IntersectionObserver with a mock method that does nothing?

**Comment by stereobooster** [comment]
well you can check if this is prerendering phase and do nothing `navigator.userAgent == "ReactSnap"` or change size of viewport
