### ISSUE TITLE
Should unit tests mock puppeteer instead actually using it?

### ISSUE THREAD

**Issue by tsantef** [stereobooster/react-snap#289]
I think tests would be easier to write and run faster if jest.mock('puppeteer') was used instead of actually using puppeteer and mocking the file system. Allowing puppeteer to fire in the unit seems like an integration test to me. I could see having one or two integration tests in a separate file that were sanity tests to insure puppeteer didn't have breaking api changes. 

I would be willing two rework the tests to follow this pattern if your interested.

**Comment by stereobooster** [comment]
Short answer: yes current tests are integration tests not unit tests. If you want to add unit tests to existing integration tests you are more than welcome (I still have 3 outstanding PRs which I need to merge and add proper support for CRA2)

**Comment by stereobooster** [comment]
I guess, I answered question so I will close this
