### ISSUE TITLE
Any guidance for React.lazy (or at least a solution for breaking changed @loadable/component)?

### ISSUE THREAD

**Issue by MacKentoch** [stereobooster/react-snap#297]
Is there a way to use react-snap with React.lazy directly?

loadable-component has evolved and focused on server side rendering.

```javascript
import { hydrate, render } from 'react-dom';
import { loadableReady } from '@loadable/component';

// ⚠️not more getState() in newer loadable-components so no more: window.snapSaveState = () => getState();

if (bootstrapedElement.hasChildNodes()) {
    loadableReady().then(() => {
      return hydrate(<Application />, bootstrapedElement);
    });
  }
  return render(<Application />, bootstrapedElement);
```

## This does not work anymore!

**Comment by stereobooster** [comment]
index.js
```
const rootElement = document.getElementById("root");
const root = ReactDom.unstable_createRoot(rootElement);
root.render(<App />);
```

App.js
```js
import React, { Component, Suspense } from "react";

const Comp = React.lazy(() => import('./Comp'))l

class App extends Component {
  render() {
    return (
      <Suspense fallback={<div>Loading...</div>} maxDuration={5000}>
        <Comp/>
      </Suspense>
    );
  }
}
```

Something like this

**Comment by MacKentoch** [comment]
Thank you @stereobooster 

But I have no success right now...

I guess I need to find a trick for filling `window.snapSaveState` object depending all React.lazy component I set?

As far as I understood react-snap will then add `<script src="some_async.js" async></script>` tags?

**Comment by MacKentoch** [comment]
Sorry I was inaccurate with `components`. I use `React.lazy` for my react-router (v4+) pages.

I'm upgrading an open source boilerplate, so I will soon push my upgrading branch if I still struggle.
It may be more comfortable to talk about then.

**Comment by stereobooster** [comment]
Suspense doesn't work without async rendering e.g.

```js
const root = ReactDom.unstable_createRoot(rootElement);
```

at least this is based on my experiments, you can double check in React documentation or ask React team about it

**Comment by MacKentoch** [comment]
Yes just hoped to find a trick.

Anyway thank you @stereobooster .

I close this no more issue (is wasn't actually).

**Comment by miguelcostero** [comment]
Hi there,

Is there a reason why I cannot fins `unstable_createRoot` on ReactDOM. I'm using version 16.6.3 (last stable).

**Comment by stereobooster** [comment]
Because it is added in React 16.6

**Comment by stereobooster** [comment]
here is working example https://github.com/stereobooster/react-lingui-example/blob/suspense/src/index.js

**Comment by MatthieuCoelho** [comment]
Still any other solution to run React-snap with async loading ? (With react lazy or loadable-components new versions ?)

**Comment by stereobooster** [comment]
https://github.com/stereobooster/react-snap/pull/338
