### ISSUE TITLE
Bug in render Customer Chat Plugin Messenger

### ISSUE THREAD

**Issue by Marcosul** [stereobooster/react-snap#303]
Hello! I use the Customer Chat Plugin on my website, but after I installed the react-snap, stop working.

From what I understand, the react-snap ran its crawler over the Messenger iframe where it generated the conflict.

How to make the mouse react do not run your crawler in the Customer Chat Plugin and just copy the script?

Follows problem playback

**- Messenger script in public/index.hml (work)**
![image](https://user-images.githubusercontent.com/4714018/49090512-08da7580-f245-11e8-8c3e-33ed0afa48f4.png)

**- Code generated by react-snap in build/index.hmtl (not work) **

![image](https://user-images.githubusercontent.com/4714018/49090626-3cb59b00-f245-11e8-8e99-4ff6db428437.png)

![image](https://user-images.githubusercontent.com/4714018/49090643-43441280-f245-11e8-8ea4-edd70bedbe9a.png)

![image](https://user-images.githubusercontent.com/4714018/49090655-49d28a00-f245-11e8-89b6-dfc01e5520df.png)

**Comment by stereobooster** [comment]
Depends on what you want to achieve. The [easiest way is to](https://github.com/stereobooster/react-snap#third-party-requests-google-analytics-mapbox-etc)

```json
"reactSnap": {
  "skipThirdPartyRequests": true
}
```

**Comment by Marcosul** [comment]
Thank you!!

But where do I enter this setting?

Em Ter, 27 de nov de 2018 14:35, stereobooster <notifications@github.com>
escreveu:

**Comment by stereobooster** [comment]
in `package.json`

**Comment by Marcosul** [comment]
It worked!!!

Thank you very much!!
