### ISSUE TITLE
How to make multilingual website in react-snap

### ISSUE THREAD

**Issue by athimannil** [stereobooster/react-snap#304]
I have multilingual website in like  http://demo.com/, http://demo.de/, http://demo.nl/ and http://demo.dk/ which done by **react-snap** 

Unfortunately SEO rendering only `demo.de` meta datas

Is there any option to use multilingual website in react-snap ?

index.js

```
const MOUNT_NODE = document.getElementById('app')
const appStructure = <Provider store={store}>
  <LanguageProvider>
    <ConnectedRouter history={history}>
      <ThemeProvider theme={theme}>
        <ABDecider>
          <App />
        </ABDecider>
      </ThemeProvider>
    </ConnectedRouter>
  </LanguageProvider>
</Provider>

const render = () => {
  if (MOUNT_NODE.hasChildNodes()) {
    ReactDOM.hydrate(
      appStructure,
      MOUNT_NODE
    )
  } else {
    ReactDOM.render(
      appStructure,
      MOUNT_NODE
    )
  }
}
```
package.json

```
      "reactSnap": {
        "source": "dist",
        "crawl": false,
        "include": [
          "/",
          "/friends"
          ]
      }
    }
}
```

**Comment by stereobooster** [comment]
In provided configuration, I guess, not. `react-snap` can generate different languages if they are defined by url, for example:

```
/de/friends
/da/friends
```

Or you need to find a way to pass language config to `<LanguageProvider>`

**Comment by stereobooster** [comment]
I will close this for now, feel free to ask more questions

**Comment by Fluorz** [comment]
I'm working on a multilingual website.

xxxxx.com => English
xxxxx.fr => French

But all URLs are the same. 

xxxxx.com/profile => profile of a user in English
xxxxx.fr/profile => profile of a user in French

When I run react-snap, it generates static HTML with default language (French). 

How can I use react-snap for a multilingual website without changing slug?
