### ISSUE TITLE
Save svg as png while crawling and use url

### ISSUE THREAD

**Issue by lachtos** [stereobooster/react-snap#307]
Hi,

I have a SPA where I generate some SVG dynamically. I use react-snap to create static pages for crawlers/bots and I would like to save the generated SVGs as PNGs to use as og:image for example for sharing purposes. What would be the best way to implement this?

Is this the correct place to ask (since I've seen questions here)?

**Comment by stereobooster** [comment]
The closest thing I can think of is 

```json
"reactSnap": {
   "saveAs": "png"
}
```

**Comment by lachtos** [comment]
This will take a screenshot of the whole page right?
I still need my pages to be saved as .html but also save embedded svg's as png's alongside the generated html and include those png's in the <head> of the .html
This seems like some kind of crawling step injection, is it possible to do with react-snap? 
Or should I insted look into injecting this step in the build flow?

**Comment by stereobooster** [comment]
you can run reac-snap twice, once you generate pngs second you generate html. What you describe is not supported out of the box, you need to write some glue code to make it work. Depending on what you want you can get away with running it twice or fork react-snap and customize it for your needs

**Comment by stereobooster** [comment]
I guess I answered the question. I will close this for now
