### ISSUE TITLE
Expansion Panel Material-UI Component stopped working after using the react-snap

### ISSUE THREAD

**Issue by Marcosul** [stereobooster/react-snap#309]
I use Material-UI (https://material-ui.com) in my website and The Expansion Panel Component stopped working after using the react-snap.

my code is the same as the example:
https://github.com/mui-org/material-ui/blob/master/docs/src/pages/demos/expansion-panels/SimpleExpansionPanel.js

How do I get the Expansion Panel Component to work using the react-snap?

Thank you.

Marco

**Comment by stereobooster** [comment]
Is it create react app 2?

**Comment by alan345** [comment]
Similar issue solved thanks to JSS: https://github.com/stereobooster/react-snap/issues/274

**Comment by stereobooster** [comment]
I guess question is answered. Feel free to open another issue if you have problems.
