### ISSUE TITLE
How to use with continuous integration?

### ISSUE THREAD

**Issue by borisyordanov** [stereobooster/react-snap#311]
## Bug Report

**Current Behavior**
The build process is failing when running in Docker with Concourse CI.
I get the following error
```
Error: Failed to launch chrome! spawn /home/app/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/home/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at ChildProcess.helper.addEventListener.error (/home/app/node_modules/puppeteer/lib/Launcher.js:333:64)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
It seems puppeteer isn't working, because dependencies are missing?

**Reproducible demo**
https://github.com/borisyordanov/react-snap-test

**Expected behavior/code**
I expected react-snap to work in a continuous integration environment

**Possible Solution**
N/A

**Additional context/Screenshots**
N/A

**Comment by stereobooster** [comment]
no reproducible example

**Comment by borisyordanov** [comment]
@stereobooster Added a repo and followed the template guidelines. Please reopen.

**Comment by stereobooster** [comment]
You report that there is issue with Docker, right? But there is no Dockerfile in repo. I will check it, but are you sure there will be an error

**Comment by stereobooster** [comment]
Just cloned it, and build with no error. Your issue is in the docker image. Try https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by borisyordanov** [comment]
I looked at the [Running puppeteer in docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker), but couldn't see how this would integrate with react-snap.

They expect `Run the container by passing node -e "<yourscript.js content as a string> as the command:`, but i don't have a `yourscript.js` equivalent, because react-snap is running puppeteer.

Lets say i set up all the dependencies like the puppeteer docs suggest, how would react-snap take advantage of that?

**Comment by stereobooster** [comment]
```json
"reactSnap": {
  "puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"],
  "puppeteerExecutablePath": "/usr/bin/chromium-browser"
}
```

**Comment by jpbourgeon** [comment]
Hello. I had a similar issue to use react-snap on AWS Amplify CI/CD environment.
I managed to make it work thanks to this issue on Puppeteer's github issues. It may help somehow

https://github.com/GoogleChrome/puppeteer/issues/765#issuecomment-445334163

**Comment by MicroBenz** [comment]
This still happens to DroneCI as well.

**Comment by TatianaRG** [comment]
@MicroBenz how did you solve this issue in DroneCI?
