### ISSUE TITLE
️💬  console.log at /: Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by xang555** [stereobooster/react-snap#319]
when i build my react project i have this error
```
️💬  console.log at /: Failed to load resource: net::ERR_CONNECTION_REFUSED
️💬  console.log at /: Failed to load resource: net::ERR_CONNECTION_REFUSED
️💬  console.log at /: Failed to load resource: net::ERR_CONNECTION_REFUSED
️💬  console.log at /: Failed to load resource: net::ERR_CONNECTION_REFUSED
✅  crawled 1 out of 1 (/)
✨  Done in 105.74s.
```
how to fix?
thanks

**Comment by stereobooster** [comment]
those are just warnings. Is there anything specific broken? Like generated HTML doesn't look like it suppose to do?

**Comment by regisBafutwabo** [comment]
I have the same issue, but at some point, while react-snap is building, it stops the build with a "Command failed with exit code 1."

How can I solve this?
