### ISSUE TITLE
__PRELOADED_STATE__ set twice on window object after build

### ISSUE THREAD

**Issue by RichardProf** [stereobooster/react-snap#320]
## Bug Report

**Current Behavior**
I use react-snap to pre-render my pages and Redux to manage my state.

// Grab the state from a global variable injected into the server-generated HTML
const preloadedState = window.__PRELOADED_STATE__ || {};

// Allow the passed state to be garbage-collected
delete window.__PRELOADED_STATE__;

// Create Redux store with initial state
const store = createStore(rootReducer, preloadedState, applyMiddleware(thunk));

// Tell react-snap how to save Redux state
window.snapSaveState = () => ({__PRELOADED_STATE__: store.getState()}); 

And then once pre-rendered, in index.html there is 2 setting of __PRELOADED_STATE__ which adds to our index.html size. We want the size of index.html as small as possible, there is no point in setting __PRELOADED_STATE__ twice:
<script type="text/javascript">window["__PRELOADED_STATE__"]={"content":{"\u002Fen-qa\u002F":{"contents":[{"contentName":"Meta","contentType":"component","fields":....></script>
and then happens again on the same page:
<script type="text/javascript">window["__PRELOADED_STATE__"]={"content":{"\u002Fen-qa\u002F":{"contents":[{"contentName":"Meta","contentType":"component","fields":....></script>

**Reproducible demo**
This is a private project

**Expected behavior/code**
In the inline script only set __PREOADED_STATE__ once.

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by stereobooster** [comment]
Last time I checked there was only one copy of data stored by reactSnap. Unless you provide reproducible example, nothing I can do about it. I'm not interested in your private project, the idea is to create repository where  it is possible to reproduce bug

**Comment by stereobooster** [comment]
Can't proceed without details
