### ISSUE TITLE
Any notes on how to set this up with a react app using webpack / babel / redux ? 

### ISSUE THREAD

**Issue by petervijeh** [stereobooster/react-snap#322]
I tried the installation steps for react-create-app,  but it doesn't appear to do anything.   Are there any examples for a react app using webpack?

thanks

**Comment by stereobooster** [comment]
Define "doesn't appear to do anything".

**Comment by stereobooster** [comment]
react-snap doesn't depend on bundler, it will work with anything, for example, webpack, rollup or parcel. Here is webpack example https://github.com/stereobooster/prerender-spa-plugin/tree/react-snap/examples/vue2-webpack-router

**Comment by khoaanh2212** [comment]
hi @stereobooster 
i'm using react-boilerplate to wrapp the project,but i can not use react-snap to prerender it.
Would you like to help?
thanks
