### ISSUE TITLE
Manually generate additional pages

### ISSUE THREAD

**Issue by julesbou** [stereobooster/react-snap#324]
_`react-snap` is really easy to use, installation went really smooth !_

---

I've 1000+ pages generated on my project. That is a lot, and it takes time to generate those pages.

I'm wondering if there's a way to render additional pages without having to generate everything from scratch again.

What I have in mind is to have a simple script like:

```bash
./snapshot.js /url-of-a-page
```
_(eventually we could also provide an array of urls for efficiency)._

This script will take care to generate a snapshot for that single page and put it in `/build` directory.

And I will take care to run this script everytime I'm adding a new page, or updating an existing one (think of a blog, where you write new articles and sometimes edit existing ones).

---

What do you think? Am I asking too much from `react-snap`?

**Comment by stereobooster** [comment]
You did it right. react-snap have limited use-cases, but you can import react-snap and create your own variations of "run.js", which would expose any options you may need

**Comment by julesbou** [comment]
Are you ok if I send a PR for this: https://github.com/graphcomment/react-snap/commit/a00b50a569f850e71af42a5a155c1e80a5542b83

It's always bad having to fork a project. It could also benefit other developers with the same use-case as me.

**Comment by stereobooster** [comment]
You can remove this file (via script) before running react-snap

**Comment by stereobooster** [comment]
This is also ok. Project intentionally doesn't use any build scripts, so it would be possible to create forks installable from github

**Comment by julesbou** [comment]
Yeah I saw it, very easy setup !
