### ISSUE TITLE
Does this work without Service Worker?

### ISSUE THREAD

**Issue by whydna** [stereobooster/react-snap#328]
Does this work with CRA without a service worker?

I don't use service workers (unregister called in index.js) but I am running into issue where it is flashing the homepage because it is loading index.html as the fallback.

How can I set it up to use the 200.html instead without SW?

@stereobooster

**Comment by stereobooster** [comment]
It is totally independent of service workers it works with and without them, as well it is independent of framework (react, vue etc), as well it is independent of bundlers (webpack, parcel etc).

You can post link to reproducible example, otherwise it is pretty hard to understand what is the issue.

**Comment by stereobooster** [comment]
I guess I answered the question. Feel free to open new issue if you have more questions
