### ISSUE TITLE
Crawl private page

### ISSUE THREAD

**Issue by juanse254** [stereobooster/react-snap#330]
When the crawler goes through the pages it gathers most of them, the ones that were not crawled can be included using the "include" on the package.json. Regardless i have a customer panel page, where the user must login first before visiting. I can login to the panel but whenever i hit refresh on a page that was not crawled before then i get a not found error.

So:

user->panel page -> refresh(f5) on browser -> not found error (because it wasn't crawled because it requires login).

Is there any workaround that doesn't involve modifying my client so if its 'react-client' i display the private page?

**Comment by stereobooster** [comment]
> Is there any workaround that doesn't involve modifying my client so if its 'react-client' i display the private page?

The only solution I can see is to prerender "shell" page (some navigation, but without content), and serve instead of 404 for your protected pages. You can also modify source of your app to serve some placeholder pages if it is in prerendering phase

**Comment by juanse254** [comment]
Is there a way to redirect to the app when hitting refresh rather than trying to reload a directory that does not exist?
when i load the page and i click through the links, the behavior is expected. When i try to refresh pages thats were the problems start, i managed to solve most of them but the private pages are an issue.

**Comment by stereobooster** [comment]
Do you use index.html or 200.html as 404 page?

**Comment by juanse254** [comment]
No, should i?

**Comment by stereobooster** [comment]
oh wait but you use 404.html (generated by react-snap), right? You need to use 404.html or index.html or 200.html as 404 page. If you use any of those as 404 page it should work.

**Comment by juanse254** [comment]
what about the real 404?  what should i set in the react-router? i can set the component to the 200.html but then what if a user hits a 404 page then it would get redirected to the index.

Or is there a setting in react-snap to set the 404 page?

**Comment by stereobooster** [comment]
❤️

**Comment by jersrej** [comment]
Hi @juanse254 How did you fix the problem? Tho I'm using a react-router-dom and CRA and S3 serverless to deploy my application. Really appreciate this, I hope you can reply. Thank you!
