### ISSUE TITLE
Can't resolve 'ws' when using {run}

### ISSUE THREAD

**Issue by vemundeldegard** [stereobooster/react-snap#336]
## Bug Report

**Current Behavior**
Trying to include pages from my CMS into the "include" part of React-snap. Getting this error: 

> ./node_modules/puppeteer/lib/WebSocketTransport.js
> Module not found: Can't resolve 'ws' in '/Users/vem/gauc/node_modules/puppeteer/lib'
> 

The only code I added was:

```
import { run } from "react-snap"

run({
  include: ['/', '/kontakt-oss', '/blogg']
})
```

**Reproducible demo**
Here is a demo https://codesandbox.io/s/zk5w0m5r3l

**Expected behavior/code**
Trying to use react-snap programatically to add routes and make sure that they are crawled. 

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by stereobooster** [comment]
The interesting part is that it is not `react-snap` fails, it is `react-scripts build`. I removed any call to `react-snap` and it still fails https://codesandbox.io/s/lqryym71m

This seems to be an issue of create-react-app. Also related https://github.com/GoogleChrome/puppeteer/issues/3466

**Comment by stereobooster** [comment]
Reported in create-react-app

**Comment by stereobooster** [comment]
I found error. You need to put this in separate file not in the code of web application

```js
import run from "react-snap";

run({
  include: ["/", "/kontakt-oss", "/blogg"]
});
```

**Comment by Dathan88** [comment]
Would you recommend putting it inside the "ws" file?
