### ISSUE TITLE
How does react-snap support multiple pages? 

### ISSUE THREAD

**Issue by baoyouwangning** [stereobooster/react-snap#347]
Now it's just reading index.html. But I have a.html b.html c.html and so on.

**Comment by stereobooster** [comment]
in `package.json`

```json
"reactSnap": {
  include: ["/a", "/b"]
}
```

**Comment by baoyouwangning** [comment]
This is my config
    "reactSnap": {
        "source": "dist/template/cash",
        "include": [
            "/cashTasks"
        ],
        "crawl": false,
        "minifyHtml": {
            "collapseWhitespace": false,
            "removeComments": false
        }
    }
   ...
   "postbuild": "react-snap"

But got Error: ENOENT: no such file or directory, open 'path to /dist/template/cash/index.html'
It read only index.html.
How to configure it for to read: /dist/template/cash/cashTasks.html ?

**Comment by stereobooster** [comment]
```
"include": [
"/cashTasks.html"
],
```

**Comment by baoyouwangning** [comment]
According to your configuration.
    "reactSnap": {
        "source": "dist/template/cash",
        "include": [
            "/cashTasksNew.html"
        ],
        "crawl": false,
        "minifyHtml": {
            "collapseWhitespace": false,
            "removeComments": false
        }
    }

This is error report
> react-snap

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'path to/dist/template/cash/index.html'

I think this is a bug.

**Comment by stereobooster** [comment]
You can open bug report with reproducible example if you think this is a bug
