### ISSUE TITLE
<script> tags don't get injected into html files.

### ISSUE THREAD

**Issue by jarandmi** [stereobooster/react-snap#348]
## Bug Report

**Current Behavior**
I have mine own react app setup with webpack (not CRA), and everything works great, excepts that the <script> tags to the javascript files don't get injected into the index.html. They do get injected into the 200.html file. I have not turned on `removeScriptTags`. I have tried both with `fixWebpackChunksIssue` and without.

**Reproducible demo**
Webpack config: https://gist.github.com/jarandmi/296b2121ac7f692dbeb7777cdf147be8

**Expected behavior/code**
I want the <sscript> tags to be injected into the html files that react-snap creates

**Possible Solution**
When i manually copy the two lines of code from 200.html to index.html the javascript works.

**Comment by stereobooster** [comment]
Most likely problem in `fixWebpackChunksIssue`. Can you provide small reproducible example?

**Comment by stereobooster** [comment]
there is also https://github.com/stereobooster/react-snap/issues/231

**Comment by jarandmi** [comment]
Demo: https://github.com/jarandmi/react-snap-demo

`yarn build` will build to `dist`folder

**Comment by stereobooster** [comment]
You use XHTML instead of HTML:

```diff
    <body>
-        <div id="root"/>
+        <div id="root"></div>
    </body>
```

which cuts out `script` tag, because script tags inserted after root div.

`react-snap` need to check for this kind of issues

**Comment by jarandmi** [comment]
Ah, thanks! That worked.
