### ISSUE TITLE
Should add link rel="preload"

### ISSUE THREAD

**Issue by ryan-ds17** [stereobooster/react-snap#35]
On adding the option `inlineCss: true` the important styles are extracted, but the main style accessed by link still has a property `rel="stylesheet"` while it should be `rel="preload"`

**Comment by stereobooster** [comment]
Are you looking at generated html or browser output?

**Comment by ryan-ds17** [comment]
the generated html

**Comment by stereobooster** [comment]
This is a strange bug. I will need reproducible demo for this.

https://github.com/stereobooster/react-snap/blob/master/index.js#L174

**Comment by ryan-ds17** [comment]
I am currently using code-splitting with react-snap
[react-snap.zip](https://github.com/stereobooster/react-snap/files/1470977/react-snap.zip)

**Comment by stereobooster** [comment]
This is what I see

```html
<link href="/static/css/app.fb2d5da5.css" rel="preload" as="style" onload="this.rel='stylesheet'">
```

which is correct

**Comment by ryan-ds17** [comment]
Which OS are you using?

**Comment by stereobooster** [comment]
I use MacOS X. Which system do you use?

**Comment by ryan-ds17** [comment]
I have two systems. The link preload works on windows 10 but not on Ubuntu.

**Comment by stereobooster** [comment]
Ok I will check Ubuntu. But this will take some time

**Comment by ryan-ds17** [comment]
Thank you.
And is it possible to use PhantomJS instead of Puppeteer?

**Comment by stereobooster** [comment]
> is it possible to use PhantomJS instead of Puppeteer?

Doesn't make any sense. PhantomJS (theoretically) have much more bugs. Puppeteer is official product of Chrome team. If we will be able to prove this is the bug of Puppeteer we can open issue in their tracker

**Comment by ryan-ds17** [comment]
This error also came up once
```
Crawled 3 out of 5 (/about)
(node:3300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ReferenceError: webpackJsonp is not defined
    at http://localhost:45674/static/js/home.c6d8ef6f.chunk.js:1:1
(node:3300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is this error causing the problem?

**Comment by stereobooster** [comment]
this error is cause by webpack dynamic import https://github.com/stereobooster/react-snap#webpack-2-and-dynamic-import

**Comment by stereobooster** [comment]
I want to change it so this option would be enabled by default see https://github.com/stereobooster/react-snap/issues/36

**Comment by ryan-ds17** [comment]
I found this on line 207 in the `fixWebpackChunksIssue` method
`const mainRegexp = /main\.[\w]{8}.js/;`

But create-react-app generates a `bundle.js`. So shouldn't the code be
`const mainRegexp = /bundle\.[\w]{8}.js/;`

**Comment by stereobooster** [comment]
which version of c-r-a do you use? I wonder when this changed

**Comment by ryan-ds17** [comment]
I am using create-react-app@1.4.1

**Comment by stereobooster** [comment]
Version of react-scripts?

**Comment by ryan-ds17** [comment]
1.0.16

**Comment by stereobooster** [comment]
still can not reproduce

this is my Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: <<-SHELL
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    apt-get update
    apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
    apt-get install -y nodejs
    apt-get install -y build-essential
    cd /vagrant
    npm install
  SHELL
end
```

```
vagrant up
vagrant ssh
cd /vagrant
npm run-script build
```

**Comment by ryan-ds17** [comment]
If I comment out `link.setAttribute("onload", "this.rel='stylesheet'");`, the rel propery is set to preload. Otherwise it remails 'stylesheet'

**Comment by stereobooster** [comment]
this is how it suppose to be. Read about async style loading https://www.npmjs.com/package/fg-loadcss

**Comment by ryan-ds17** [comment]
I reproduced it on Windows 8.1 and Arch Linux. Seems to be platform specific.
I also get this error on Windows 8.1
```
ERROR: The process with PID 3544 (child process of PID 3896) could not be terminated.
Reason: The operation attempted is not supported.
(node:3092) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: taskkill /pid 3896 /T /F
ERROR: The process with PID 3544 (child process of PID 3896) could not be terminated.
Reason: The operation attempted is not supported.
```

**Comment by ryan-ds17** [comment]
`link.setAttribute("onload", "this.rel='stylesheet'");`

In the above line, the onload code is being executed as I also tried another line
`link.setAttribute("onload", "this.rel='alternate stylesheet'");`

The rel property was set to
`rel="alternate stylesheet"`

**Comment by stereobooster** [comment]
As of windows problem - I can not help with that. I do not have windows machine. Try to look similar problem in puppeteer.

As of `link.setAttribute` not sure what you want to change. This is intended behaviour. Read about async css load technique by Filament Group, Inc. You can easily change this, by creating your own fork. This npm package is installable via git - it does not have compilation steps.

**Comment by ryan-ds17** [comment]
Is it possible to omit pages to be prerendered. Like the profile page is user-specific so ideally that should not be preloaded.

**Comment by stereobooster** [comment]
but how crawler gets to this page? don't you need to be loged in?
