### ISSUE TITLE
How-To Prerender dynamically changed content (BLOG)

### ISSUE THREAD

**Issue by matrad** [stereobooster/react-snap#350]
Hello,

we currently build a news-page with react where we started from the basic "create-react-app". 

Because of SEO we need to think for a way to generate the page-metas / content and to render them without javascript (facebook preview, whatsapp preview, google, ...).

Our react-page uses:
 - styled components
 - react helmet
 - react-router

The idea of react-snap is to prerender "all" pages and to update them with a static build. In our case we have thousand of articles what comes from a database and are updated/added time by time. (>50 daily). SEO is really important for this page.

My idea is also to apply prerendering for all user-agents, not only for google, ... (how prerender.io does). So the concept of react-snap is perfect with the hydrate-feature.

In theory react-snap would do the job but we need to add a method to start react-snap as a server where we can "proxy" the request (like on prerender.io) and get a html "on-the-fly" and save the output to file. The next time this page is served directly from the statically saved prerendered html. When updating a post the prerendered file could be deleted and re-rendered again.

Other solutions I already tried:
 - prerender.io: no compatibility with styled-components (css not loaded)
 - react-snap: no possibility to dynamically render pages without starting a build

My current solution:
 - deploy application with react build
 - laravel in front of react-page what adds the meta to the html head to the generated react index.html script.
 - generate sitemaps for all post pages
 - problem: content is not in the html, SEO results may be not as good as if I prerender the entire page?

What is the best practice to prerender a news-blog like mine? (with react-snap / other tools) do you have any experiences with pages like mine?

**Comment by stereobooster** [comment]
I would say you need either: SSR or prerender on the fly (like `prerender.io`) only for search bots (so even if css is wrong, the text is still there).

**Comment by matrad** [comment]
@stereobooster I also thought about this - but the search-engines do not only crawl the text-content, and make also a visual ranking (button sizes, mobile friendly, ...) so is this a good idea?

**Comment by stereobooster** [comment]
there are other solutions in this area (not just prerender.io). You can try one of those https://github.com/stereobooster/react-snap/blob/master/doc/alternatives.md#seo-only-server-prerenderers

**Comment by stereobooster** [comment]
I guess I answered the question
