### ISSUE TITLE
not able to use this for google bots

### ISSUE THREAD

**Issue by The-Code-Monkey** [stereobooster/react-snap#352]
## Bug Report

**Current Behavior**

This shouldn't cause the normal client side code to break, what i currently have is an nginx server that builds it and serves whatever the index.html file is to the client no matter the route what i want to do is if a google bot tries to craw the site i just point the bot to a different folder and it can get the files, due to what react-snap does it stops the normal client side rendering from working.

**Expected behavior/code**

should duplicate the build folder to __snapshots__ and then run the stuff in there so you don't get the glitch i have

**Additional context/Screenshots**

i think this is a much better option as i want google to see prerendered pages but the front end user to see the client side rendered ones.

**Comment by stereobooster** [comment]
There are a lot of solutions in this area see list here https://github.com/stereobooster/react-snap/blob/master/doc/alternatives.md#seo-only-server-prerenderers. Even though react-snap can be refactored to do this, I don't see reason to do this because those solutions already exist
