### ISSUE TITLE
Is there a way to use react-snap with react's concurrent mode?

### ISSUE THREAD

**Issue by ilanbm** [stereobooster/react-snap#366]
When I'm trying to use react-snap with the new concurrent mode, using `createRoot(rootElement, { hydrate: true }).render`, the hydration doesn't work...

How do I use react-snap with concurrent mode?

**Comment by stereobooster** [comment]
React concurrent mode is experimental feature, so there is no guarantee it will work see https://github.com/stereobooster/react-async-issue.
