### ISSUE TITLE
How to host/deploy

### ISSUE THREAD

**Issue by Svish** [stereobooster/react-snap#368]
I've looked around in the README and in the docs, but can't really find anything regarding how to actually host this?

Is that because it actually really properly just is a matter of uploading the contents of the build folder to anywhere? It seemed to work fine to run `npx serve -s build`, but what I have currently is basically just the basic `create-react-app`.

I'm thinking maybe it really is just a matter of uploading to somewhere, but even if that is the case, it would be good for a newb like me if that was written clearly somewhere in e.g. the readme? 🤔

**Comment by stereobooster** [comment]
This tool assumes that you already have working SPA as static website and you simply want to improve load performance and SEO. You add it in the middle of building and you can deploy website as you previously did.

More documentation is always good. PRs are welcome

**Comment by stereobooster** [comment]
I will close this ticket in favour of https://github.com/stereobooster/react-snap/issues/117. PRs are welcome 👍
