### ISSUE TITLE
Doesn't work in AWS Amplify

### ISSUE THREAD

**Issue by cvillafraz** [stereobooster/react-snap#388]
## Bug Report

**Current Behavior**
I'm deploying a react-snap app to AWS Amplify. It keeps throwing the error "error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory"
![aws](https://user-images.githubusercontent.com/34899726/59161700-f83c6f00-8ab3-11e9-9f1c-a7f1a30cd8fb.png)

**Reproducible demo**
I cannot add a demo since it's a client's private repo

**Expected behavior/code**
react-snap works in my dev environment, but not in AWS Amplify

**Comment by stereobooster** [comment]
This issue with puppeteer. See https://github.com/GoogleChrome/puppeteer/issues/765 or https://medium.com/mockingbot/run-puppeteer-chrome-headless-on-ec2-amazon-linux-ami-6c9c6a17bee6
