### ISSUE TITLE
Generate file not working while using react-helmet

### ISSUE THREAD

**Issue by adamsaparudin** [stereobooster/react-snap#391]
## Bug Report

**Current Behavior**
Not updating title or meta tag from helmet

**Reproducible demo**
[sample repo](https://github.com/adamsaparudin/react-snap-helmet)

`yarn install` and `yarn build`

**Expected behavior/code**
Expecting generated version is have tag from helmet.
From example code, generated version `build/index.html` should have `<title>Test</title>` instead of `<title>React App</title>`

**Comment by stereobooster** [comment]
Can't reproduce

```sh
git clone https://github.com/adamsaparudin/react-snap-helmet.git
cd react-snap-helmet
yarn
yarn build
yarn react-snap
```

`build/index.html`

```html
<title>Test</title>
```
