### ISSUE TITLE
Doesn't support fragments

### ISSUE THREAD

**Issue by jonaskkristensen** [stereobooster/react-snap#393]
## Bug Report
It doesn't support React fragments 
**Current Behavior**
Works perfectly in development. Doesn't get shown when deployed
```
<>
  <div>
  // Will be shown correctly under dev and deploy
    {state && (<Icon />)
  </div>
  // Will be shown correctly under dev but NOT deployed
  {state && <Icon />}
</>
```

**Expected behavior/code**
Expects to give the same result as development

**Possible Solution**

Meanwhile changing `<>` with `<div>` will fix the problem

**Comment by stereobooster** [comment]
No reproducible example. Will reopen as soon as somebody will post reproducible example
