### ISSUE TITLE
Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by alexvandervegt** [stereobooster/react-snap#395]
No matter what i try, 1.23.0 or 1.10.0. I always get this error:

Am i doing something wrong?

 error at / { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/alexvdvegt/Sites/DirectBasing/Core/direct-basing/webapp/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/Users/alexvdvegt/Sites/DirectBasing/Core/direct-basing/webapp/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/alexvdvegt/Sites/DirectBasing/Core/direct-basing/webapp/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/Users/alexvdvegt/Sites/DirectBasing/Core/direct-basing/webapp/node_modules/puppeteer/lib/helper.js:112:23)
    at fetchPage (/Users/alexvdvegt/Sites/DirectBasing/Core/direct-basing/webapp/node_modules/react-snap/src/puppeteer_utils.js:232:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

**Comment by stereobooster** [comment]
Hard to tell do you use built-in server or external? Can you post reproducible example?

**Comment by alexvandervegt** [comment]
I use the build in server and very basic setup from the readme. Only the index.js is edited to hydrate and thats it.

**Comment by stereobooster** [comment]
First time I see this error. This is not the same error as https://github.com/stereobooster/react-snap/issues/318. If you would post example, I can run it. If it would work on my machine then the problem is in your machine. The server for some reason doesn't work

**Comment by alexvandervegt** [comment]
The server is starting, because i see some console.log messages from my CRA:

$ react-snap
️️️💬  console.log at /: Content is cached for offline use.
️️️💬  console.log at /: This web app is being served cache-first by a service worker. To learn more, visit https://bit.ly/CRA-PWA
🔥  error at / { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

**Comment by alexvandervegt** [comment]
When i use headless = false then it boots and i see it is crashing at an user form:
️️️💬  console.log at /: [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) %o

Is it possible to give some kind of sitemap to react-snap? I dont need my login page to snapped.

**Comment by alexvandervegt** [comment]
After fixing all autocomplete suggestions puppeteer does not crash anymore :)

**Comment by nickjuntilla** [comment]
> After fixing all autocomplete suggestions puppeteer does not crash anymore :)

Where do you find the auto-complete suggestions?

**Comment by kamami** [comment]
Same Problem

**Comment by insivika** [comment]
same problem

**Comment by yellowbang** [comment]
same problem

**Comment by dang1412** [comment]
same problem with firebase page, is there any option to use the result after a certain time ex. 20s, no need to wait for network idle then throw error, should use the current result instead of throwing error.

**Comment by JulianPhillips** [comment]
same problem

**Comment by everdrone** [comment]
same problem
