### ISSUE TITLE
support waitUntil options

### ISSUE THREAD

**Issue by hardfist** [stereobooster/react-snap#398]
## Feature Request

**Is your feature request related to a problem? Please describe.**
My page call some network request after component mount, which will return random picture, which will affect my  background,
current watiUntil default value is 'networkidle0', which will render page after network finish, which will cause setting background using network response, which doesn't meet my needs, so I want to snapshot page before network finish, which use 'load' for 'waitUntil', but waitUntil is not configurable 
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.

**Comment by stereobooster** [comment]
This feature will allow users [to shoot in the foot](https://idioms.thefreedictionary.com/shoot+in+the+foot). Which would cause more confusion down the line, which I don't want to deal with (I'm tired of asking for reproducible demo). That is why I don't want this feature
