### ISSUE TITLE
saveAs option should accept empty string

### ISSUE THREAD

**Issue by linonetwo** [stereobooster/react-snap#40]
For now, option "saveAs" only accept some file extension, but for dynamic router, only file without extension will work.

I have to manually remove extension like this:

```sh
for file in *.html; do mv $file ${file%.html}; done
```

**Comment by stereobooster** [comment]
saveAs - is a type of file e.g. html or png. Empty string doesn't make much sense here.

Your problem is in `path`. Use path with the `/` in the end and `react-snap` will generate `path/index.html`.

**Comment by stereobooster** [comment]
And I want to change this behaviour see ticket https://github.com/stereobooster/react-snap/issues/36

**Comment by linonetwo** [comment]
Awesome, that solves it.

**Comment by linonetwo** [comment]
I use 

```
"reactSnap": {
    "include": ["/", "/404", "about/team/", "/about/hire/", "/about/introduction/", "/about/salon/"]
  }
```
 To set up this.

**Comment by stereobooster** [comment]
`react-snap` not able to discover those links?

I mean you should use `path/`in `<Link>` (I suppose you are using react-router)

**Comment by linonetwo** [comment]
Oh, thanks for reminding that. Of course, it works.
