### ISSUE TITLE
Routing broken on page refresh

### ISSUE THREAD

**Issue by rohan-deshpande** [stereobooster/react-snap#402]
## Bug Report

`react-snap@1.10.0`

**Current Behavior**
(Using `react-router-4`) When I navigate to a route other than `/`, for example, `/about`, and refresh the browser, the static site seems to mount components for `/` while also mounting things for the route component

**Reproducible demo**
https://github.com/creativelifeform/nebula-web/tree/feature/react-snap

**Expected behavior/code**
It should render the route and route component correctly

**Possible Solution**
N/A

**Additional context/Screenshots**
On navigate to route:

<img width="1578" alt="Screen Shot 2019-08-14 at 7 21 53 am" src="https://user-images.githubusercontent.com/1079637/62978411-8fcb8e80-be64-11e9-974f-0c9593faa7bf.png">

On refresh route:
<img width="1582" alt="Screen Shot 2019-08-14 at 7 22 02 am" src="https://user-images.githubusercontent.com/1079637/62978427-978b3300-be64-11e9-9203-3f05d539ba03.png">

**Comment by stereobooster** [comment]
how is your server configured?

**Comment by rohan-deshpande** [comment]
Happens locally using the default server suggested by CRA

**Comment by stereobooster** [comment]
the problem is in the server try this instead

```
npm run build
npx http-server -p 8000 build
```

**Comment by rohan-deshpande** [comment]
Interesting, do you have any idea what specific thing is causing this? Missing a trailing slash or something?

**Comment by gvlatko** [comment]
@rohan-deshpande did u figure out how to configure the server? this is happening also to me on aws s3 hosted site
