### ISSUE TITLE
CRA 3 not loading/hydrating javascript: The resource (*.chunk.js) was preloaded using link preload but not used within a few seconds from the window's load event.

### ISSUE THREAD

**Issue by kmcaloon** [stereobooster/react-snap#438]
So everything is working beautifully apart from my app not hydrating after loading as you can see on my demo site: https://neutrino-server.site/courses/basic-flight-training/tampa-fl/

Not sure where to even start here. I took a look at similar issues i.e. #264 but nothing seems to be working for me. For what it is worth I am using a custom craco config and running react-snap programmatically after everything is finished: 

```
    compiler.hooks.done.tap( 'React Snap Plugin', stats => {

      ReactSnap.run( {
        inlineCss: true,
        asyncScriptTags: true,
        //fixWebpackChunksIssue: false,
      } );

    } );
```

The problem occurs no matter how I configure the options. Any idea how I can start troubleshooting?

**Comment by pacarvalho** [comment]
@kmcaloon Were you able to solve your issue?

**Comment by kmcaloon** [comment]
Sorry @pacarvalho this was a while back and have since switched to Gatsby for other reasons. I don't think I was able to solve this though.

**Comment by nandorojo** [comment]
I'm still seeing this issue. Did anyone fix it?
