### ISSUE TITLE
Animation is not working correctly

### ISSUE THREAD

**Issue by roy1210** [stereobooster/react-snap#466]
## Bug Report

Hi teams!
I added react-snap for my project. However, the Hero section animation(made by framer motion) is not working correctly if using react-snap. Kindly please help to advise if any configuration in "reactSnap" at `packaging.json` are useful for this case.

### Before used reactSnap: (Expected result)

https://swingby.network/en/

### After installed reactSnap:

https://swingby-landingpage-hwmucwoq7.now.sh/en/

https://gyazo.com/e8df459d5c091b36829eafd606b21679

**Comment by ricky11** [comment]
did you solve this?
