### ISSUE TITLE
Client Side Components

### ISSUE THREAD

**Issue by redxtech** [stereobooster/react-snap#487]
## Feature Request

**Describe the solution you'd like**
A way to exclude components/elements from being prerendered. Either a wrapper component to wrap around components that we only want rendered on client side or an attribute/directive that tells react-snap to ignore all the component/element's children.
The attribute might be the best way to keep this framework agnostic though.

**Describe alternatives you've considered**
I've tried using `vue-client-only` but it appears as though the components are still rendered by react-snap.

**Teachability, Documentation, Adoption, Migration Strategy**
Surround the component you want to be client-only with the wrapper component OR add the `snap-client-only` (for example) diractive/attribute to the component you want to be client-only.

**Comment by stereobooster** [comment]
```js
const Snap = ({ children }) => {
  const isReactSnap = navigator.userAgent === 'ReactSnap';
  return isReactSnap ? null : children
}
```

**Comment by redxtech** [comment]
Perfect, thanks.
