### ISSUE TITLE
does this work with react-apollo?

### ISSUE THREAD

**Issue by karsens** [stereobooster/react-snap#51]
does this work with react-apollo?
sorry if this is a stupid question.

**Comment by stereobooster** [comment]
I see why not. There is real browser behind scene. If this thing works in browser it will in react-snap. The only question is how you gonna rehydrate the generated code.

**Comment by jidan70** [comment]
Hi @stereobooster, but is there a way to increase the time react-snap crawls your page? Because i'm using react-apollo but react-snap renders the page before all my request with react-apollo is done.

**Comment by stereobooster** [comment]
Do you have example application that I can test?

There is a `waitFor` option the same as [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options-args). But obviously this is a hack and there should be a better way to do this, like https://github.com/geelen/react-snapshot/pull/30

**Comment by jidan70** [comment]
Ok thanks, i will create a small example. So is this better solution to be sure that everything we need has been rendered in the react app?

**Comment by stereobooster** [comment]
There is no better solution so far

**Comment by stereobooster** [comment]
Heh it is actually possible to rehydrate Apollo store, so you can do something like this. (Not an exact code)

```js
// Grab the state from a global variable injected into the server-generated HTML
const preloadedState = window.__APOLLO_STORE__

// Allow the passed state to be garbage-collected
delete window.__APOLLO_STORE__

const client = new ApolloClient({
  initialState: preloadedState,
});

// Tell react-snap how to save state
window.snapSaveState = () => ({
  "__APOLLO_STORE__": client.store.getState()
});
```

**Comment by jidan70** [comment]
Hi @stereobooster thank you very much, i'll look at this

**Comment by stereobooster** [comment]
Will close this for now. Feel free to reopen

**Comment by zomars** [comment]
I figured it out, I'll share it here for reference:

```js
// Grab the state from a global variable injected into the server-generated HTML
const preloadedState = window.__APOLLO_STORE__;

// Allow the passed state to be garbage-collected
delete window.__APOLLO_STORE__;

const client = new ApolloClient({
  initialState: preloadedState,
});

// Tell react-snap how to save state
window.snapSaveState = () => ({
  __APOLLO_STORE__: client.client.readQuery({
    query, // you can pass any query you want to prerender here
  }),
});

const query = gql`
  query ReadTodo {
    todo(id: 5) {
      id
      text
      completed
    }
  }
`;
```

**Comment by vishnup95** [comment]
@zomars Where did you add this to?

**Comment by zomars** [comment]
@vishnup95 I've updated my previous comment for more clarity. But, IDK if this still working TBH. I've moved into other projects.
