### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by BrunoQuaresma** [stereobooster/react-snap#519]
Using `react-snap` on Vercel I'm getting this error:

```

$ react-snap
--
16:49:34.528 | Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
16:49:34.529 | at Launcher.launch (/vercel/workpath1/node_modules/puppeteer/lib/Launcher.js:119:15)
16:49:34.529 | at async crawl (/vercel/workpath1/node_modules/react-snap/src/puppeteer_utils.js:188:19)
16:49:34.529 | at async run (/vercel/workpath1/node_modules/react-snap/index.js:647:3)
16:49:34.546 | error Command failed with exit code 1.

```

**Comment by Giridhar108** [comment]
Same

**Comment by t4sk** [comment]
sudo npm install puppeteer --unsafe-perm=true --allow-root

https://stackoverflow.com/questions/53997175/puppeteer-error-chromium-revision-is-not-downloaded#53998266

**Comment by BrunoQuaresma** [comment]
I think there is no solution for this yet, right?

**Comment by BrunoQuaresma** [comment]
Better discussion about this error: https://github.com/vercel/vercel/issues/2357#issuecomment-626236409

**Comment by ezekiel747** [comment]
Just encountered this error. I tried what was suggested on that thread on vercel, without success.
Although puppeteer was listed as installed, what i did was to **remove node_modules folder** and re-run **npm install**
Worked for me, just leaving this in case someone needs it.
