### ISSUE TITLE
The site appears for a few seconds, then disappears

### ISSUE THREAD

**Issue by Giridhar108** [stereobooster/react-snap#528]
## Bug Report

The site appears for a few seconds, then disappears and these errors appear in the console.
![image](https://user-images.githubusercontent.com/68693488/112587570-9f240380-8e1f-11eb-941e-cdbf4eb30238.png)

"reactSnap": { 
    "include": [ "/"],
    "inlineCss": true,
    "puppeteer": { "cache": false },
    "puppeteerArgs": [ "--no-sandbox", "--disable-setuid-sandbox" ] }
}

**Comment by Giridhar108** [comment]
I resolve this. I read the documentation more carefully.

**Comment by ricky11** [comment]
what did you do?
