### ISSUE TITLE
Who uses it

### ISSUE THREAD

**Issue by jamesli2021** [stereobooster/react-snap#569]
The 3 URLs link in the Readme are not longer active. Should you update who uses it?

Updated. Using Shoelace Carousel.

**Comment by komxvl** [comment]
Hi. I using this in my project, but I have some issues with routers((

**Comment by Keshavdulal** [comment]
@komxvl do you still recommend it in 2023?
I have a client with b2c product built on react and has poor SEO.

Thinking of using this instead of doing a full migration to nextjs but the state of react-snap and support to React v17 or v18 doesn't look promising.

**Comment by komxvl** [comment]
I think it's better to use nextjs, because nextjs has a great community, and can resolve some unexpected problems

**Comment by jamesli2021** [comment]
I think AstroJS is neat, solves my 100/100 lighthouse, have been building sites since Astro 2.0 released, no more CLS.

https://docs.astro.build/en/guides/migrate-to-astro/from-nextjs/

https://astro.build/

**Comment by fadiakkad** [comment]
It's used in this project : 
https://do-calculate.com/
