### ISSUE TITLE
Question about react-native-web

### ISSUE THREAD

**Issue by gianluca-santexgroup** [stereobooster/react-snap#65]
Hello!

I don't really want to file a bug or anything, I was just wondering if you have tested this with react-native-web.

I've been working on a project where we have some universal components that we created using react-native-web, so in order to render the application I have to do something like:

```js
const ComponentInst = (
  <RootAppComponent
    store={store}
    persistor={persistor}
    history={history}
  />
);

if (rootEl.hasChildNodes()) {
  ReactNative.hydrate(ComponentInst, rootEl);
} else {
  ReactNative.render(ComponentInst, rootEl);
}
```

At the beginning of the project we set up the configuration and everything seemed good, the development workflow and the building were working as expected, although we didn't have much content to test it on. The whole time while in development we haven't had any problems with the whole setup, we've been using react-native-web and styled-components.

Now we have deployed an early version of the app and when we built the application we noticed that some stuff wasn't being rendered correctly. I can't really find differences in the generated css, but for some elements the computed styles in the inspector are just different. For example some container elements lost their height.

I know in the [react-native-web documentation](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md) they use the react-native to do the server side rendering, so maybe what I'm trying to do is not reasonable.

I could get rid of react-snap to "fix" this and maybe later on just do traditional server side rendering as per their docs but it would be really convenient to fix this keeping this approach because we also want to deploy using S3 and CloudFront.

So maybe is there a way to integrate this? Could you point me in the right direction or just tell me if it's not possible, it would save me some time.

Thanks for reading this!

**Comment by stereobooster** [comment]
> I was just wondering if you have tested this with react-native-web

No. But if your project works in the browser `react-snap` should work - there is a real browser behind the scene. You possibly catch a bug in `react-snap` or rehydration process.

There was one bug like this in `react-snap` - html doctype wasn't saved to snapshot. Try latest version of `react-snap`. Create reproducible demo if you want me to look into it.

**Comment by gianlucacandiotti** [comment]
Alright, will give me sometime in the weekend to try and reproduce this in another repository. Thanks for the response.

**Comment by stereobooster** [comment]
Closing due inactivity. Feel free to reopen if you have more questions
