### ISSUE TITLE
How to handle images(question)

### ISSUE THREAD

**Issue by jasan-s** [stereobooster/react-snap#70]
this is not a bug, rather a question.
I am using some `img` tags with images with image loading like so: 
`import four from 'media/images/landingPage/four.png'`

but in the static html the images seem broken.  even my `placeholder src ` is not rendering in the static page. 

SO my question is how do I handle images with the lib?

**Comment by stereobooster** [comment]
create-react-app should work without any modifications, so `import four from 'media/images/landingPage/four.png'` should work too. If it doesn't then this is a bug. Please provide a reproducible example.

**Comment by stereobooster** [comment]
Images works as expected https://github.com/stereobooster/an-almost-static-stack/commit/ab33a308d28f8332815ecfae02a2af7377d47c39#diff-ec2264c3e640e18e894de598903998bb

If this is not the case for you, please post reproducible example.
