### ISSUE TITLE
/./shell.html pageerror: Error: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#98]
Extracted from https://github.com/stereobooster/react-snap/pull/96

To reproduce use any CRA project, set `"homepage": ".",` .

Duplicate https://github.com/stereobooster/react-snap/issues/59

**Comment by stereobooster** [comment]
This error happens when browser requests `js` (or `json`?) file and gets `html` instead. Can be solved by code similar to [WebpackDevServerUtils.js](https://github.com/facebookincubator/create-react-app/blob/0ec41350db21a2e87d6d8288ecacca45227f368a/packages/react-dev-utils/WebpackDevServerUtils.js)

**Comment by KingScooty** [comment]
Also seems to happen if a script's src 404's.

**Comment by loganpowell** [comment]
I'm getting this as well. Also tried the solution in https://github.com/stereobooster/react-snap/issues/59, but that only worked for the home page and its assets. Any further guidance towards

>code similar to WebpackDevServerUtils.js. 

?

**Comment by stereobooster** [comment]
You have 404 for some of the js scripts. Open page in browser and find it.

Propper bugfix would to add logging for 404 js documents

**Comment by stereobooster** [comment]
Added logging in `1.11.3`. Need to rework server to actually fix all edge cases. Want to get some ideas from https://github.com/facebook/create-react-app/blob/19e0bb1881e24fb1ee3fe421413d4d87e67f68dd/packages/react-dev-utils/WebpackDevServerUtils.js

**Comment by stereobooster** [comment]
Close in favour of #153
