### ISSUE TITLE
material-ui / jss / dynamic imports

### ISSUE THREAD

**Issue by aheissenberger** [stereobooster/react-snap#99]
The default class names (.jss123) created by jss will be merged from different dynamic imports which breaks the design.

**Setup:**
* Material-UI (v1.0.0-beta-26) https://material-ui-next.com
* JSS https://github.com/cssinjs/jss

**Solution:**
replace default name generator (http://cssinjs.org/js-api/?v=v9.5.0#generate-your-own-class-names) with a variation which uses random strings as part of the class name and wrap your app with this HOC.

```Javascript
import React, { Component } from 'react';
import JssProvider from 'react-jss/lib/JssProvider';
import { create } from 'jss';
import preset from 'jss-preset-default';
//import createGenerateClassName from 'material-ui/styles/createGenerateClassName';

import Layout from './components/pages/layout';

const createGenerateClassName = () => {
  let counter = 0
  return (rule, sheet) => `c${Math.random().toString(36).substring(2, 4) + Math.random().toString(36).substring(2, 4)}-${rule.key}-${counter++}`
}

const jss = create(preset());
// Custom Material-UI class name generator for better debug and performance.
jss.options.createGenerateClassName = createGenerateClassName;

function App() {
  return (
    <JssProvider jss={jss}>
      <Layout />
    </JssProvider>
  );
}

export default App;
```

please add this to the recipe section of your docs

**Comment by stereobooster** [comment]
I do not fully understand problem. I will need to investigate. Thanks for the tip

**Comment by stereobooster** [comment]
Here is example project https://github.com/stereobooster/material-ui/tree/react-snap. I do not see any issues, except `ripple-visible: [object Object]` but this is unrelated

**Comment by stereobooster** [comment]
Yes I was able to reproduce. I missed that this is reproducible with dynamic import. Strange thing. I wonder how JSS works with SSR.

**Comment by stereobooster** [comment]
Thank you @aheissenberger

**Comment by nimahkh** [comment]
> function App() {

perfect, this solution was amazing , thanks a lot

**Comment by ifier** [comment]
Can you help me please? I'm using React.lazy() instead :(

```
import React from "react";
import { hydrate, render } from "react-dom";
import App from "./redux/redux-wrapper";
import * as serviceWorker from "./serviceWorker";

const rootElement = document.getElementById("root");
if (rootElement.hasChildNodes()) {
  hydrate(<App />, rootElement);
} else {
  render(<App />, rootElement);
}

window.snapSaveState = () => {
  Array.from(document.querySelectorAll("[data-jss]")).forEach(elem =>
    elem.setAttribute("data-jss-snap", "")
  );
};

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

```

**Comment by bartosz-lobejko-trabr** [comment]
Another solution

`
const generateClassName = createGenerateClassName({
  productionPrefix: navigator.userAgent === 'ReactSnap' ? 'snap' : 'jss',
});

<StylesProvider jss={jss} generateClassName={generateClassName}>
    <Layout/>
</StylesProvider>
`

**Comment by matthewkwong2** [comment]
A much easier solution for `material-ui` users.

For people who are using `material-ui` v4, wrap the components in `<NoSsr/>`.

For `material-ui` v5, which is currently in the alpha stage, this will no longer be an issue in the future since it is migrating to `emotion`.

**Comment by oseisaac** [comment]
> `<NoSsr/>`.

@matthewkwong2  
how do ou know what components to wrap with `<NoSsr/>` with a large application

**Comment by matthewkwong2** [comment]
> > `<NoSsr/>`.
> 
> @matthewkwong2
> how do ou know what components to wrap with `<NoSsr/>` with a large application

If you want to do pre-rendering on a large scale project, then react-snap is not the right tool. It is more or less an experiment and prove of concept and have a lot of imperfection. Instead, you should use a proper solution like Gatsby.

**Comment by oseisaac** [comment]
Yeah that makes sense but the project is already a long way ahead

**Comment by marcuiulian13** [comment]
In our case of using `react-snap`, with `react-jss`, we realised that for some reason, the styles created while running `react-snap` (so Puppeteer) are missing some selectors and styles.

Here is the solution we ended up with, that works every time:
```
import React from 'react';
import { render, hydrate } from 'react-dom';
import { createGenerateId, JssProvider, SheetsRegistry } from 'react-jss';

import App from './App';

const rootElement = document.getElementById('root');
if (rootElement && rootElement.hasChildNodes()) {
  hydrate(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    rootElement,
    () => {
      const reactSnapStyles = document.getElementById('react-snap-styles');
      reactSnapStyles?.parentNode?.removeChild(reactSnapStyles);
    },
  );
} else {
  const registry = new SheetsRegistry();
  const generateId = createGenerateId();

  render(
    <JssProvider registry={registry} generateId={generateId}>
      <React.StrictMode>
        <App />
      </React.StrictMode>
    </JssProvider>,
    rootElement,
    () => {
      if (navigator.userAgent === 'ReactSnap') {
        const badStyles = document.querySelectorAll('[data-jss]');
        badStyles.forEach((cssStyle) => cssStyle.parentNode?.removeChild(cssStyle));

        const style = document.createElement('style');
        style.innerHTML = registry.toString();
        style.setAttribute('id', 'react-snap-styles');

        const head = document.querySelector('head');
        head.appendChild(style);
      }
    },
  );
}
```

Basically, when we're running the app with `react-snap`, we remove the generated `react-jss` styles (since they might be broken) and we append a `<style id="react-snap-styles">` to head, with all the styles we collected in the `SheetsRegistry`. Then, when we get to rehydrate the app, after everything is rendered (and snap generated new styles), we remove the `#react-snap-styles` element.

I hope this helps people that might end up here with a similar issue.
